### ISSUE TITLE
Incorrect queue updates with certain enqueue actions

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#435] opened 2023-05-07 18:28 UTC
### Describe the Bug/Crash

Sorry for the bad title.
Let's say I have 2 albums A1 and A2, with the songs A1.1, A1.2 and A1.3 and A2.1 and A2.2.
Start by playing A1. The queue correctly contains A1.1, A1.2, A1.3.
Now use the add to queue feature on A2. Now the queue screen displays for me: A1.1, A1.2, A.1.3, A2.1 and **A1.3**. The last song is wrong.
However, just continue hearing or just play the last song (which is displayed wrong): A2.2 is played, as the intended behavior. It's just shown wrong.

### Describe the intended behavior

Display what is played correctly

### What android version do you use?

Android 12

### What device model do you use?

Stock Android One

### Bug report

/

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-05-07 18:32
Probably an edge-case with the new queue update logic. I will attempt to reproduce it when I get time. In the meantime, a screen recording of the actions you took would be very helpful.

**Comment by sgreenden** [comment] 2023-05-27 02:16
I have this issue too, this is one of the biggest issues I've had as it basically makes the queue feature unusable

**Comment by OxygenCobalt** [comment] 2023-05-29 15:57
I figured out the cause of this issue, it was a really embarrassing error I made where I would visually update the queue like "Play next" was selected, even when "Add to queue" was selected. This should be fixed now.

**Closed by OxygenCobalt** 2023-05-29 15:57 UTC
Labels: bug, ui
