### ISSUE TITLE
Tolerate inconsistent MusicBrainz ID usage

### ISSUE THREAD

**Issue by alphanerdgen** [OxygenCobalt/Auxio#555] opened 2023-08-29 16:15 UTC
### Describe the Bug/Crash

Under the 'Artists' tab, Auxio's creating multiple entries for some artists in spite of them having the correct tags. I checked a track's properties and found that the artist's name is getting added again in the 'Artists' field within parentheses. This issue isn't occuring in other music players.

![Screenshot_Auxio 1](https://github.com/OxygenCobalt/Auxio/assets/83120103/8126f754-2dc7-443a-934c-b6752823943d)

![Screenshot_Auxio 2](https://github.com/OxygenCobalt/Auxio/assets/83120103/c6f0b7a6-196c-414d-871b-b8fd3e61ba5f)

![Screenshot_Auxio 3](https://github.com/OxygenCobalt/Auxio/assets/83120103/2c34f2ae-e2a3-4f52-97e6-69c7046d9305)

Intelligent sorting is enabled.

Version: 3.2.0 [F-Droid]

### Describe the intended behavior

The app shouldn't duplicate tag details.

### What android version do you use?

Android 12

### What device model do you use?

Samsung Galaxy

### Bug report

No bug report.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-08-29 16:26
This is caused by your music library partially using MusicBrainz IDs (MBIDs). Auxio considers artists without MBIDs and artists with MBIDs to be different, and groups them separately. There's not really a better behavior I can use regarding this without causing more subtle bugs, so I just go with the strategy that results in the most obvious issues.

If I were to guess at the cause, this is because you've used two different taggers. One is applying information from MusicBrainz, including MBIDs and sort names (Which is what you are seeing with artists like "Godsmack (Godsmack)". I should probably make that clearer...). One applies more basic tag information.

I would highly recommend either removing all MusicBrainz IDs from your library, or using an autotagger like Picard or Beets that will universally apply MBID information.

**Comment by OxygenCobalt** [comment] 2023-08-30 02:54
Now that I think about it, it could actually be possible to handle inconsistent MBIDs better without bugs if I were to tweak the music grouping algorithm. I'll re-open to investigate.

**Comment by KraXen72** [comment] 2023-09-03 13:27
i think this would be good. The benefit of seeing incorrect tags is great, but i think a setting that ignores them would be very useful (for when you know some stuff is incorrectly tagged, but don't have time to fix it, and now can't properly play one album or something because half the stuff is in another artist entry)

**Comment by OxygenCobalt** [comment] 2023-09-03 16:59
I honestly don't see myself doing that @KraXen72 here. My workaround should not have any secondary issues hopefully.

**Comment by KraXen72** [comment] 2023-09-03 17:03
so auxio will be able to merge artists without MBID's and artists with MBID's?

**Comment by OxygenCobalt** [comment] 2023-09-03 17:05
Yes, my idea is that with some changes I would be able to gracefully degrade if MBID usage is inconsistent. If the app finds that a given artist name corresponds to a null MBID and a non-null MBID, it will simply move the songs from the null MBID to the songs with a non-null MBID @KraXen72.

**Comment by KraXen72** [comment] 2023-09-03 17:07
ah, that's a great idea. 
what about the scenario where 2 artists (let's say A and B) have several songs and the same display name (there are over 20 artists with the name Atlas, for example). If these artists have a different MBID, but some songs don't have a mbid, where will they go?

**Comment by KraXen72** [comment] 2023-09-03 17:07
> My reasoning is that even though this increases the risk of merging different artists with the same name, someone already aware of that should be tagging appropriately anyway, so it shouldn't affect them.
  
 ah okay. i guess my question is an edge-case then. I am still interesting in the resolution logic though.

**Comment by OxygenCobalt** [comment] 2023-09-03 17:11
> what about the scenario where 2 artists (let's say A and B) have several songs and the same display name (there are over 20 artists with the name Atlas, for example). If these artists have a different MBID, but some songs don't have a mbid, where will they go?

They will be moved to the artist with the most songs. This is to reduce the likelihood I'm merging into the wrong artist, as I'd imagine that the artist with a lot of songs is the one more likely to be inconsistent compared to one that has a few songs.

**Comment by Elmi77** [comment] 2023-09-22 10:35
As my bug has been closed as duplicate of this one: what is described there seems NOT to be the reason for my troubles. All filed have been tagged with the same version of MusicBrainz Picard. On the other hand: the only visible difference between the two "Oxygene Trilogy" albums is the date. In my opinion it does not make sense to use this date as sorting criteria.

**Comment by Elmi77** [comment] 2023-09-22 10:35
As my bug has been closed as duplicate of this one: what is described there seems NOT to be the reason for my troubles. All filed have been tagged with the same version of MusicBrainz Picard. On the other hand: the only visible difference between the two "Oxygene Trilogy" albums is the date. In my opinion it does not make sense to use this date as sorting criteria.

**Comment by Elmi77** [comment] 2023-09-22 10:36
As my bug has been closed as duplicate of this one: what is described there seems NOT to be the reason for my troubles. All filed have been tagged with the same version of MusicBrainz Picard. On the other hand: the only visible difference between the two "Oxygene Trilogy" albums is the date. In my opinion it does not make sense to use this date as sorting criteria.

**Comment by OxygenCobalt** [comment] 2024-11-08 06:27
Done, will arrive in 4.0.0 @KraXen72 @alphanerdgen

**Closed** 2024-11-08 06:27 UTC
Labels: bug, music, non-criticial
