### ISSUE TITLE
Album length is shifted left

### ISSUE THREAD

**Issue by nphantasm** [OxygenCobalt/Auxio#349] opened 2023-02-03 15:39 UTC
### Describe the Bug/Crash

1. Open any album
2. Album length under the artists name is shifted left no matter it's length and collides with the separator between number of songs and album length

![ed965461-1ce2-4488-b815-d8b703d1957d](https://user-images.githubusercontent.com/81529977/216642759-8d5b8f09-92a9-4e00-bfbf-3a7475e9823f.jpg)

### Describe the intended behavior

Album length should be not be colliding with the separator.

### What android version do you use?

Android 12

### What device model do you use?

realme 9 (realme UI 3.0)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-02-03 15:41
Duplicate of #205. Realme phones are garbage and have had this formatting bug for awhile. Nothing I can do to fix it.

**Closed by OxygenCobalt** 2023-02-03 15:41 UTC
Labels: bug
