### ISSUE TITLE
Crash when playing certain MP3 files in 3.0.0

### ISSUE THREAD

**Issue by Koruy** [OxygenCobalt/Auxio#303] opened 2022-12-30 20:14 UTC
### Describe the Bug/Crash

Kicks out of the app when playing some songs

### Describe the intended behavior

Play mp3 files and do not throw out of the application

### What android version do you use?

Android 12

### What device model do you use?

Honor 70

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2022-12-30 21:41
There's not enough information for me to determine the issue. Can you provide a stack trace?

If you don't know how, you can follow these steps:
1. Use a desktop/laptop to download the android platform tools from [here](https://developer.android.com/studio/releases/platform-tools).
2. Extract the downloaded file to a folder.
3. Enable USB debugging on your phone ([Instructions](https://developer.android.com/studio/command-line/adb#Enabling)), and then connect your phone to a laptop. You will get a prompt to "Allow USB debugging" when you run the logcat command. Accept this.
4. Open up a terminal/command prompt in that folder and run ./adb -d logcat AndroidRuntime:E *:S`
5. Copy and paste the output to this issue

**Comment by KraXen72** [comment] 2023-01-01 20:25
this also happens for me but very rarely, i'll to observe the circumstances and maybe take a stack trace with adb

**Comment by e-zk** [comment] 2023-01-02 02:44
I've been getting a crash frequently. I don't know if it's relevant to this issue or if its different. 

```
type: crash
package: org.oxycblt.auxio:24
process: org.oxycblt.auxio
processUptime: 8751 + 196 ms

java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.google.android.exoplayer2.metadata.id3.TextInformationFrame.populateMediaMetadata(TextInformationFrame.java:690)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda19.run(R8$$SyntheticClass:220)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by OxygenCobalt** [comment] 2023-01-02 03:20
Okay, seems like an internal player issue. Can you send a sample file @e-zk?

**Comment by e-zk** [comment] 2023-01-02 04:18
I don't know what file is causing it. Every time it happens my whole library is on shuffle. 

I'll try and narrow it down but its tricky because as soon as it'll start playing it'll crash

**Comment by e-zk** [comment] 2023-01-02 04:24
@OxygenCobalt file that causes error attached. 

```
type: crash
package: org.oxycblt.auxio:24
process: org.oxycblt.auxio
processUptime: 9400 + 224 ms

java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.google.android.exoplayer2.metadata.id3.TextInformationFrame.populateMediaMetadata(TextInformationFrame.java:468)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda19.run(R8$$SyntheticClass:220)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

[Serene.mp3.zip](https://github.com/OxygenCobalt/Auxio/files/10329983/bsd.u.-.Serene.mp3.zip)

**Comment by OxygenCobalt** [comment] 2023-01-02 04:28
Okay, thanks. I'll check it out when I wake up @e-zk. 

Note: You might also want to try the [latest CI artifact](https://github.com/OxygenCobalt/Auxio/actions/runs/3819281488) to see if the error is different at all. I changed the internal player code a bit that may affect how this issue manifests (if it manifests at all).

**Comment by Donkey-Doug** [comment] 2023-01-02 12:23
I cannot play audio that has an album cover since version 3.0.0.

**Comment by OxygenCobalt** [comment] 2023-01-02 15:15
Okay, so I can reproduce the both of your crashes on 3.0.0 release, but not in the latest development builds. I think the issue was a bug in my ExoPlayer fork that I fixed when I backported the merged changes.

Care to try out the [latest CI artifact](https://github.com/OxygenCobalt/Auxio/actions/runs/3819281488) @Donkey-Doug @e-zk? I think it should work now.

**Comment by Donkey-Doug** [comment] 2023-01-02 15:24
The issue is fixed for me.

**Comment by e-zk** [comment] 2023-01-03 01:19
@OxygenCobalt yep. issue fixed for me on that CI apk

**Comment by OxygenCobalt** [comment] 2023-01-03 01:25
Okay, great. I'll start work on a new patch release.

**Closed by OxygenCobalt** 2023-01-03 01:25 UTC
Labels: bug, music
