### ISSUE TITLE
[Feature Request] Playback rate control

### ISSUE THREAD

**Issue by GanerCodes** [OxygenCobalt/Auxio#469] opened 2023-06-05 13:25 UTC
### Description

A setting or slider that allows me to change the playback rate, with an option to compensate pitch shifting or not.

### Other implementations

A setting

### Benefit

Sometimes podcasts/songs just need to be sped up (or slowed down)

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-06-06 02:06
This is a duplicate of prior issues. Auxio is a music player, not a podcast client. I don't really get use from differing playback speeds, so I doubt I'll ever add this. Sorry.

**Closed by OxygenCobalt** 2023-06-06 02:06 UTC
Labels: enhancement

**Comment by Gamer750** [comment] 2024-05-05 23:00
I would also like this feature
