### ISSUE TITLE
Music loading fails on all Huawei devices

### ISSUE THREAD

**Issue by tsafs** [OxygenCobalt/Auxio#592] opened 2023-10-02 18:25 UTC
### Describe the Bug/Crash

1. Own Huawei P20 Smartphone
2. Open app
3. Grant permissions
4. See this error

- It also doesn't work when I use the whitelist option and select a specific folder to load music from

### Describe the intended behavior

Should load music

### What android version do you use?

Android 10

### What device model do you use?

Huawei P20

### Bug report

java.lang.NullPointerException
	at org.oxycblt.auxio.music.fs.BaseApi29MediaStoreExtractor$Query.populateFileInfo(SourceFile:53)
	at org.oxycblt.auxio.music.fs.BaseMediaStoreExtractor.consume(SourceFile:126)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreJob$1.invokeSuspend(SourceFile:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:19)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-10-02 18:38
Seems like #120 actually exists on all Huawei P20 models, not just the ones below Android 10, sigh...

Thanks for reporting this.

**Comment by ChristianCiach** [comment] 2023-10-05 21:44
Same issue with a Huawei Matepad 11 (2021), updated to HarmonyOS 3.0 (which is essentially Android 12 as reported by CPU-Z). Stacktrace is exactly the same as shown by OP above.

**Comment by OxygenCobalt** [comment] 2023-10-17 03:22
Sorry for the wait. Here's a debug APK that should dump some valuable information for me in the music loading stack trace. Try it and report the new error that pops up @tsafs @ChristianCiach.

[Auxio_MoreLogging.zip](https://github.com/OxygenCobalt/Auxio/files/12923922/Auxio_MoreLogging.zip)

**Comment by ChristianCiach** [comment] 2023-10-17 21:57
@OxygenCobalt Here is the new stacktrace:

```
java.lang.Exception: Directory not present [StorageVolume: Interner Speicher null]
	at org.oxycblt.auxio.music.fs.BaseApi29MediaStoreExtractor$Query.populateFileInfo(MediaStoreExtractor.kt:520)
	at org.oxycblt.auxio.music.fs.BaseMediaStoreExtractor.consume(MediaStoreExtractor.kt:207)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreJob$1.invokeSuspend(MusicRepository.kt:416)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```

**Comment by OxygenCobalt** [comment] 2023-10-17 22:08
Huh. So it doesn't provide the relative path of all things. I guess I'll have to make a huawei-specific music loader that has the #120 fix and a mitigation for this too, probably by using the older absolute path field.

**Comment by Ox55** [comment] 2023-11-19 06:59
Hello, I hope you are well. The bug you mentioned about Huawei devices is due to limitations in reading and writing applications in the Huawei ecosystem, here are the steps to solve it.

1. Open Auxio
2. Go to Settings/Music Folders
3. Choose a folder were your music will be stored (I recommend choosing /Music directory then move your tracks to this directory).

**Comment by OxygenCobalt** [comment] 2023-11-20 02:48
Weird. So Huawei has some kind of scoped storage on steroids where it will flat out refuse path data unless you've been granted file system access to them @Ox55? In that case, #322 should also eventually allow me to completely resolve that.

**Comment by ChristianCiach** [comment] 2023-11-20 12:54
I can confirm that the setup described by @Ox55 works on my Matepad 11 on HarmonyOS 3.0. That's a neat workaround, thanks!

**Comment by Ox55** [comment] 2023-11-20 17:06
> Weird. So Huawei has some kind of scoped storage on steroids where it will flat out refuse path data unless you've been granted file system access to them @Ox55? In that case, #322 should also eventually allow me to completely resolve this without stupid hacks (Albeit for now I'll do the workaround from prior internally).

Huawei's system has some particularities, for example, the permission to read and write to the /data and /obb directories (tested in Harmony OS 2.0 and EMUI 12) without the use of a computer or the famous split-screen method, commonly used to copy information to these directories. A pop-up to choose directories in the first configuration of Auxio, or a function so that in the first configuration, Auxio looks for the /storage/emulated/0/Music directory, which is the default music directory in most Android-derived builds, can help solve this problem, as mentioned in [#322](https://github.com/OxygenCobalt/Auxio/issues/322).

[@OxygenCobalt](https://github.com/OxygenCobalt)

**Comment by OxygenCobalt** [comment] 2024-01-01 06:48
Care to try this APK @tsafs @Ox55 @ChristianCiach @Admin31019?

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13803761/Auxio_Canary.zip)

I had to make a guess on how to determine if the device is made by huawei, and I don't know if harmonyos will get angry at my workaround or not, so it still might not be working.

**Comment by ChristianCiach** [comment] 2024-01-01 13:05
@OxygenCobalt Doesn't work for me:

```
java.lang.IllegalStateException: MediaStore discovery is deadlocked
	at org.oxycblt.auxio.music.MusicRepositoryImpl.indexImpl(MusicRepository.kt:494)
	at org.oxycblt.auxio.music.MusicRepositoryImpl.access$indexImpl(MusicRepository.kt:222)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$1.invokeSuspend(Unknown Source:16)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Ox55** [comment] 2024-01-01 13:24
> @OxygenCobalt Doesn't work for me:
> 
> ```
> java.lang.IllegalStateException: MediaStore discovery is deadlocked
> 	at org.oxycblt.auxio.music.MusicRepositoryImpl.indexImpl(MusicRepository.kt:494)
> 	at org.oxycblt.auxio.music.MusicRepositoryImpl.access$indexImpl(MusicRepository.kt:222)
> 	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$1.invokeSuspend(Unknown Source:16)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
> 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> ```

Hi @ChristianCiach, do the same steps that i told for the original Auxio version and will work.

**Comment by Ox55** [comment] 2024-01-01 14:25
@OxygenCobalt Isn't loading music.

**Comment by OxygenCobalt** [comment] 2024-01-01 17:17
That stack trace is probably in error (I have other types of deadlock checks), care to try this one @tsafs @Ox55 @ChristianCiach @Admin31019?

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13805400/Auxio_Canary.zip)

**Comment by ChristianCiach** [comment] 2024-01-01 17:33
@OxygenCobalt Now it just says "No music found" (in german), even though their is plenty of music on the device that gets found by other music players. I've tried again after clearing the app data, but no change.

Even worse: The workaround to add my music folder to the list of music folders in the settings doesn't work anymore; still "No music found". But no crashes.

**Comment by OxygenCobalt** [comment] 2024-01-01 18:24
Oh, wait, my change created a new bug @ChristianCiach. Let me fix that.

**Comment by OxygenCobalt** [comment] 2024-01-01 19:20
Third times the charm. Can you try this @tsafs @Ox55 @ChristianCiach @Admin31019?

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13805656/Auxio_Canary.zip)

**Comment by ChristianCiach** [comment] 2024-01-01 19:23
@OxygenCobalt

```
java.lang.Exception: DeviceLibrary creation failed: java.lang.IllegalArgumentException: Invalid raw null: No path
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(MusicRepository.kt:471)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

Better luck next time :)

**Comment by ChristianCiach** [comment] 2024-01-01 19:24
Configuring the music folder prevents the crash, but results in "No music found" again.

**Comment by ChristianCiach** [comment] 2024-01-01 19:31
Maybe I could grant you some kind of remote access to my device, using TeamViewer or something like that? I don't use my tablet a lot, so I wouldn't mind you controlling my device unattended.

**Comment by OxygenCobalt** [comment] 2024-01-01 19:32
No, I don't really need to remote pilot a device. I am getting a grasp of the issue and can simply send another test APK that allows me to debug the 

Anyway, that's not a good sign at all. That implies that Huawei might also be denying me the `DATA` path, because it really does just hate media apps. I wonder what the probability is of their music app just *happening* to not have these restrictions? What a horrible OEM.

Here's a test APK that allows me to confirm that hunch. Report the stack trace @ChristianCiach:

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13805680/Auxio_Canary.zip)

**Comment by ChristianCiach** [comment] 2024-01-01 19:35
```
java.lang.Exception: DeviceLibrary creation failed: java.lang.Exception: Tag extraction failed: java.lang.Exception: MediaStore extraction failed: e
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(MusicRepository.kt:471)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by OxygenCobalt** [comment] 2024-01-01 19:36
Templating error :facepalm:. One second

**Comment by OxygenCobalt** [comment] 2024-01-01 19:43
Trying again:

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13805703/Auxio_Canary.zip)

**Comment by OxygenCobalt** [comment] 2024-01-01 19:47
@ChristianCiach

**Comment by ChristianCiach** [comment] 2024-01-01 19:48
```
java.lang.Exception: DeviceLibrary creation failed: java.lang.Exception: Tag extraction failed: java.lang.Exception: MediaStore extraction failed: java.lang.IllegalStateException: Could not find volume for path hw_product/media/Pre-loaded/Music/Dream_It_Possible.flac (tried: [InternalVolumeImpl(storageVolume=StorageVolume: Interner Speicher), ExternalVolumeImpl(storageVolume=StorageVolume: Samsung-Speicherkarte (7434-8B91))])
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(MusicRepository.kt:471)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

Thank you for putting up with us Huawei device owners, by the way. I would totally understand if you had decided to just not bother with these devices. 

But for all of its shortcomings (mainly the missing Google services), I still think this is a great device. I picked up this tablet two years ago for like 200 Euro (keyboard and pen included) and I think it's still incredible value.

**Comment by OxygenCobalt** [comment] 2024-01-01 19:51
`hw_product/media/Pre-loaded/Music/Dream_It_Possible.flac`

...I have never seen this path before. I'm going to quickly confirm the volumes aren't spitting out this path, and if so then I'm just going to hard-code this prefix and hope things don't break.

Quick question: Is your music on an SD card or on your internal storage.

**Comment by ChristianCiach** [comment] 2024-01-01 19:52
The music is on the internal storage under `/Music`.

**Comment by OxygenCobalt** [comment] 2024-01-01 19:53
Alright, so I assume then this is Huaweis specific /storage/emulated/0 equivalent, and they just didn't update the volume to indicate that path. I need to confirm this

**Comment by ChristianCiach** [comment] 2024-01-01 19:56
That being said, I cannot find a file named "Dream_it_possible.flac" anywere inside this folder (or anywhere else, really). Let me check where it gets the filename from. This is weird..

**Comment by OxygenCobalt** [comment] 2024-01-01 19:58
Perhaps it's actually a default Huawei ringtone thing?

**Comment by OxygenCobalt** [comment] 2024-01-01 19:59
Another APK: 
[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13805735/Auxio_Canary.zip)

**Comment by OxygenCobalt** [comment] 2024-01-01 20:00
@ChristianCiach

**Comment by ChristianCiach** [comment] 2024-01-01 20:03
Before I try your new APK, check this out: Yes, `Dream_it_possible.flac` is actually the sole music file that is just shipped by Huawei as part of the System. Huawei's stock music player shows the song and also its path:

![Screenshot_20240101_210053_com huawei music](https://github.com/OxygenCobalt/Auxio/assets/19341644/6e35cc04-92ff-47fb-a3f6-ab4a89b18755)

I can probably not even delete it, because no file browser lets me access the root directory.

**Comment by OxygenCobalt** [comment] 2024-01-01 20:18
Wow. So huawei just...doesn't list a volume for it's preloaded stuff. Wonderful. In this case I'm just going to have to filter them out then.

**Comment by Ox55** [comment] 2024-01-01 20:19
Recent Huawei devices do not have an SD card slot, the methodology that Huawei used is a proprietary SD card that is inserted into the SIM slot, which is why most, if not all, recent Huawei devices use two SIM cards.
The track 'Dream it Possible' comes by default on Huawei devices, the system added the track in a path not reachable by the normal user.
To listen to the track 'Dream is Possible' just open the default music application, the music will be there if you haven't deleted it, as the system allows this but the music will return when you format the device, and yes, the original Music app has high privileges.

Note: You'll need to use the default Music app to delete this track.

**Comment by OxygenCobalt** [comment] 2024-01-01 20:26
I think I'm not going to filter them out. I'll leave them in, but with a kind of "Other volume" signifier. The songs will sadly only be removable currently by including another music folder.

Also, the fact that this exists and can't be resolved via a file manager seems like justification for Auxio to have song deletion. I'm opening an issue for that. Thanks Huawei, you've successfully convinced me to accept a feature that I would normally reject.

**Comment by ChristianCiach** [comment] 2024-01-01 20:30
I don't think Auxio needs a deletion feature. This is a single file that can easily deleted using the stock music player. Any other files can be deleted using a regular file explorer or through MTP. I think it's sufficient to just filter files without volumes or add it to a virtual album -- your choice, of course. I just don't feel a deletion feature is a reasonable reaction to such an edge case :)

**Comment by OxygenCobalt** [comment] 2024-01-01 20:45
Alright, try this APK @ChristianCiach 

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13805902/Auxio_Canary.zip)

**Comment by ChristianCiach** [comment] 2024-01-01 20:54
@OxygenCobalt It works! It just works, even after deleting all app data and without configuring any included folders. 

Great work, and thanks again for going out of your way to support out exotic devices!

**Comment by OxygenCobalt** [comment] 2024-01-01 21:02
Fantastic. Thank you so much for holding through all the debug builds, it's great when someone is this receptive to testing.

**Closed by OxygenCobalt** 2024-01-01 21:02 UTC
Labels: bug, music

**Comment by ChristianCiach** [comment] 2024-01-01 21:10
> it's great when someone is this receptive to testing.

Likewise! Huge respect for being this responsive when it comes to answering bug reports and providing debug builds! This reminds me of simpler times when I had enough time to closely interact with the users of my ROM over at XDA. Anyway, thanks for Auxio and keep up the good work!
