### ISSUE TITLE
Error Scanning Music Library with Song Featuring the Same Artist Twice

### ISSUE THREAD

**Issue by polyester2023** [OxygenCobalt/Auxio#646] opened 2023-12-21 03:37 UTC
### Describe the Bug/Crash

1. Install version 3.2.1
2. Have a song featuring the same artist twice or maybe more
3. Scan the music library and see the error

### Describe the intended behavior

It should cause any error with the same artist multiple times. I have included the file below.

### What android version do you use?

Android 13

### What device model do you use?

Xiaomi 12

### Bug report

`java.lang.IllegalStateException: Malformed song 18. Requiem Cantata _祈り_ - 削除 (Vo. 削除).flac: Artist grouping mismatch at org.oxycblt.auxio.music.device.DeviceLibraryImpl.<init>(SourceFile:258) at okhttp3.ConnectionPool.create(SourceFile:1042) at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl$create$1.invokeSuspend(Unknown Source:12) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8) at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)`

[music.zip](https://github.com/OxygenCobalt/Auxio/files/13734835/music.zip)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-12-21 03:43
Duplicate of a prior regression (#614).

**Closed by OxygenCobalt** 2023-12-21 03:43 UTC
Labels: bug
