### ISSUE TITLE
iTunes lossless (AAC/m4a) missing time

### ISSUE THREAD

**Issue by DanHolli** [OxygenCobalt/Auxio#875] opened 2024-09-23 06:44 UTC
Tracks that were imported via iTunes from CDs using lossless AAC don't have have an end time

This makes scrobbling impossible as any attempt will reset to the beginning on the song

It also lacks bitrate information but that's less important

**Comment by DanHolli** [comment] 2024-09-23 14:07
Interestingly it is only in the app. AA and the media control card don't have this issue

**Comment by rahul-gill** [comment] 2024-09-24 08:10
Media store stores the duration of ALAC files as 0 instead of the actual length. If we see the length of any ALAC song in the app, it shows zero.

 In the player ui, it's possible to get the length from exoplayer, but for the properties section, some other solution is required

**Comment by OxygenCobalt** [comment] 2024-09-28 16:24
I think this is a dupe of #661. Basically what @rahul-gill said. Worse still, ExoPlayer only populates the duration during playback rather than allowing me to dry-extract it like other metadata. I have to figure out what to patch on my own assuming that a recent update hasn't added it.

**Closed by OxygenCobalt** 2024-09-28 16:24 UTC
Labels: bug, playback
