### ISSUE TITLE
Lyrics support request 

### ISSUE THREAD

**Issue by U1M450W** [OxygenCobalt/Auxio#286] opened 2022-12-02 09:32 UTC
Hi developer.... I'm gonna request lyrics support for auxio...in upcoming version....

**Comment by OxygenCobalt** [comment] 2022-12-02 15:28
Duplicate of #190, and countless others. This is not currently planned because:

1. Most of my music is instrumental, so I gain no benefit from lyrics. When it does have lyrics, I tend to memorize them through enough listens.
2. Most lyrics are LRC files, which I cannot obtain on modern android due to "scoped storage" limitations. This would restrict users to the less intuitive `SYLT` for MPEG files and some made-up format for Vorbis or FLAC, which I doubt would be sensible. Fetching them externally is also a non-option, as I have made a promise for Auxio to not have internet access.
3. I have only seen music apps get buggier when they add lyrics, due to issues with the playback position, how lyrics have to be crammed into the playback UI, and so, so many state issues. I want to add useful things that won't horribly break the app in the process.

**Closed by OxygenCobalt** 2022-12-02 15:28 UTC
