### ISSUE TITLE
Change cover view in album, artist tab

### ISSUE THREAD

**Issue by Github-contribute** [OxygenCobalt/Auxio#168] opened 2022-06-22 11:24 UTC
#### Describe the feature you want to implement:
Want to change view grid mode on cover pic 1x1,2x4,3x9. For album tab square, view for artist tab circle.

#### Is your feature request related to a problem? Please describe:
No

#### Do other music players handle this? If so, how?
Retro Music

#### Due Diligence:
- [ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ ] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [ ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment] 2022-06-22 14:48
Duplicate of #156. I do not want to add additional display options out of the fear that it would severely bloat the app, as others request more and more options for how they want items to be customized. Eventually, you end up like Retro, where there are a dozen display options and none of them work well. Sorry.

**Closed by OxygenCobalt** 2022-06-22 14:48 UTC
Labels: enhancement
