### ISSUE TITLE
Artists shows up twice with different albums

### ISSUE THREAD

**Issue by icewind1991** [OxygenCobalt/Auxio#600] opened 2023-10-11 12:38 UTC
### Describe the Bug/Crash

One of the artists in my collection is listed twice:

![artists](https://github.com/OxygenCobalt/Auxio/assets/1283854/21cf9c49-a3e8-457d-a613-f52c7d90e693)

### Describe the intended behavior

All albums of an artist are grouped together

### What android version do you use?

Android 13

### What device model do you use?

Samsung S9 (LineageOS)

### Bug report

The artist shown in the song info seems to be correct for both:

![song1](https://github.com/OxygenCobalt/Auxio/assets/1283854/f2749171-ce2c-4962-b532-8d93adcbb6ed)
![song2](https://github.com/OxygenCobalt/Auxio/assets/1283854/c4838914-ecb8-4554-a4c3-c3e1adb43eeb)

And kid3 also shows that the artist tag is identical:

![Screenshot_20231011_142223](https://github.com/OxygenCobalt/Auxio/assets/1283854/07ada496-d72e-4b26-bba4-e6e4c4fba074)

None of the albums have MusicBrainz ids

The only difference I can think of is that the album listed separately is mp3 while the 6 albums listed together are all flac

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-10-11 14:55
I know you probably already checked, but are you sure that *all* of the tracks don't have MusicBrainz IDs? Just checking one track is not sufficient.

**Comment by OxygenCobalt** [comment] 2023-10-11 15:52
Alright, this is extremely strange. Could you provide sample files @icewind1991? Just strip the audio while keeping the exact tag configuration. Please provide the entirety of *Haven* and *Karma*, if possible in the case that the issue only arises with the interaction between music files.

**Comment by OxygenCobalt** [comment] 2023-10-11 17:29
Ugh, another weird cache issue. I can never seemingly reproduce those, so I'll close this for now. Please let me know if it happens again.

**Comment by OxygenCobalt** [comment] 2023-10-18 18:09
I just realized: This might be an ordering problem. By reloading your music files, you implicitly changed their ordering in the music database, and while Auxio normally tries to make ordering consistent, there might be some kind of way the Kamelot audio files were ordered that caused Auxio to create duplicate artists. Reopening to investigate.

**Comment by blackwind** [comment] 2023-11-02 08:30
I can confirm this issue. Multiple Taylor Swifts in my library, one of which is mixed into the "S" section for some reason. Pixel 7 Pro, Android 14, latest Auxio, meticulously tagged files, doesn't happen in any other player.

**Comment by OxygenCobalt** [comment] 2023-11-02 18:25
Please show the tags that [kid3](https://kid3.kde.org) displays when you select all of the Taylor Swift audio files in your library @blackwind. It should look a lot like [this reply](https://github.com/OxygenCobalt/Auxio/issues/600#issuecomment-1757977508). I have feeling that you're using several taggers, as one of the Taylor Swift entires being in the "S" section implies a sort name being detected. These tend to be added by auto-taggers that use online music databases.

**Comment by curbia** [comment] 2024-06-02 21:38
I also have this issue, with multiple artists. Their tags are all identical.

![image](https://github.com/OxygenCobalt/Auxio/assets/87792521/f2a849c6-89f9-41a3-b3d4-8298d1159f56)
![image](https://github.com/OxygenCobalt/Auxio/assets/87792521/e2f12264-b403-407a-a6d7-e594498ff98b)
![image](https://github.com/OxygenCobalt/Auxio/assets/87792521/47fa78be-ef86-4c8c-98e4-fd9ca0eeeea4)

I can't see what is making this happen on the outlier albums.

This is not a caching issue in my case — this is a brand-new phone, and I just installed Auxio for the first time.

**Comment by OxygenCobalt** [comment] 2024-06-02 21:43
> I also have this issue, with multiple artists. Their tags are all identical.
> 
> ![image](https://github.com/OxygenCobalt/Auxio/assets/87792521/f2a849c6-89f9-41a3-b3d4-8298d1159f56)
> ![image](https://github.com/OxygenCobalt/Auxio/assets/87792521/e2f12264-b403-407a-a6d7-e594498ff98b)
> ![image](https://github.com/OxygenCobalt/Auxio/assets/87792521/47fa78be-ef86-4c8c-98e4-fd9ca0eeeea4)
> 
> I can't see what is making this happen on the outlier albums.
> 
> This is not a caching issue in my case — this is a brand-new phone, and I just installed Auxio for the first time.

Please provide sample files @curbia. Remove the audio, keep the tags identical.

**Comment by curbia** [comment] 2024-06-03 02:13
Unsure how to do that. All Google results offer is background noise removal or vocal removal.

**Comment by OxygenCobalt** [comment] 2024-06-03 02:15
> Unsure how to do that. All Google results offer is background noise removal or vocal removal.

Use a program like Audacity to clear the audio, and then use kid3 to copy the tags from the original file to the cleared one (Audacity will mangle the metadata otherwise). I'm assuming you have a desktop, doing this on mobile is much harder.

**Comment by eylenburg** [comment] 2024-06-07 09:05
I have encountered the same problem. Auxio 3.4.3, Pixel 8, Android 14 (GrapheneOS).

It only happens rarely but when it happens I fail to see any difference in the artist. The first screenshot is Mp3tag and there's no trailing spaces or anything. It's exactly the same Artist and Album Artist. But Auxio shows is as two separate artists with the same name.

![Screenshot_20240607_095714](https://github.com/OxygenCobalt/Auxio/assets/84839316/39c78e3e-9c43-49fb-abc7-9ad359cc3fe3)
![Screenshot_20240607-095748](https://github.com/OxygenCobalt/Auxio/assets/84839316/3e623b14-fc27-4718-be06-87ec3a00bfee)

**Comment by OxygenCobalt** [comment] 2024-06-08 05:25
> I have encountered the same problem. Auxio 3.4.3, Pixel 8, Android 14 (GrapheneOS).
> 
> It only happens rarely but when it happens I fail to see any difference in the artist. The first screenshot is Mp3tag and there's no trailing spaces or anything. It's exactly the same Artist and Album Artist. But Auxio shows is as two separate artists with the same name.
> 
> ![Screenshot_20240607_095714](https://github.com/OxygenCobalt/Auxio/assets/84839316/39c78e3e-9c43-49fb-abc7-9ad359cc3fe3)
> ![Screenshot_20240607-095748](https://github.com/OxygenCobalt/Auxio/assets/84839316/3e623b14-fc27-4718-be06-87ec3a00bfee)
> 
> 

Please follow the instructions I brought up earlier so I can get sample files @eylenburg. Also let me know if you have any MusicBrainz tags.

**Comment by OxygenCobalt** [comment] 2024-06-09 20:05
@curbia I can't use those files. Whatever audio editor you used made files that are unusable by Auxio and ffmpeg. Can you try again with silence rather than total audio removal?

**Comment by curbia** [comment] 2024-06-11 00:42
[City and Colour.zip](https://github.com/user-attachments/files/15780490/City.and.Colour.zip)

This time I did a bit of searching and instead of using Audacity and then copying the tags over (lots of work) I ran this command:
`for f in *.mp3 ; do ffmpeg -i "${f}" -c copy -aframes 1 "/path/to/output/${f}"; done`

Which, if these files work, should hopefully help others package their files up more easily. Only works for MP3 files, and I found it easiest to have no spaces in the file names or output path.

**Comment by OxygenCobalt** [comment] 2024-06-11 02:56
I've reproduced this issue with the new files @curbia. Will try to fully investigate once I have the time.

**Comment by OxygenCobalt** [comment] 2024-06-11 03:04
I think the issue is basically that you have two different conventions for your MBIDs @curbia, one is the OGG convention (MUSICBRAINZ_WHATEVER_ID) and the other is the ID3 convention (MusicBrainz Whatever Id). I'm not parsing out the former since I thought that was OGG-only, which then lead to an MBID inconsistency that lead to an artist split (See #555, I'm working on a fix for that since it's really not a good failure mode). I can fix it on my end by considering both tags, and you can fix it on your end by simply unifying your MBID use by deleting them all or autotagging with something like MusicBrainz Picard or beets.

**Comment by OxygenCobalt** [comment] 2024-06-11 03:08
This still really isn't related to @icewind1991's issue sadly, but since we hit a dead end on that front and I haven't encountered any reproductions, I might just assume it was a blue moon cache issue (cosmic rays perhaps? haha) and close this when I fix @curbia's problem. Unsure.

**Comment by curbia** [comment] 2024-06-11 13:04
These *are* all autotagged from MB Picard. Very odd.

**Comment by OxygenCobalt** [comment] 2024-06-14 01:34
If you first tagged OGG files with Picard and then converted to MP3 later, these tags would likely go untranslated (most conversion software is not really intimate with tags). Picard may have never updated them after that @curbia.

Alternatively, Picard may decide that the OGG and ID3 conventions are interchangeable and decides nothing needs to be done if it finds the OGG convention in ID3 tags.

**Closed** 2024-06-14 02:43 UTC
Labels: bug, device-specific, critical
