### ISSUE TITLE
Album cover not displaying

### ISSUE THREAD

**Issue by nswerhun** [OxygenCobalt/Auxio#51] opened 2021-10-09 03:45 UTC
#### Describe the bug/crash:
MP3 files which I have tagged myself are not displaying the album art. They display fine in other applications, but not in Auxio.

#### Steps To Reproduce the bug/crash:

1. Download [this](https://raw.noahsw.xyz/kyrie.mp3) file as an example.
2. Open up on your computer in your media player of choice and see the album cover.
3. Put it onto your phone and open it up in Auxio.
4. See that the album cover is not displayed.

#### Screenshots:
Auxio app:
![new](https://user-images.githubusercontent.com/24984195/136643151-9cd4a7ae-1144-4608-bca6-90602c4b7a80.png)

Picard (linux) clearly showing album image:
![2021-10-08-223632_570x425_scrot](https://user-images.githubusercontent.com/24984195/136642920-2b8211f4-6ee3-4bab-a0b8-87960f24e435.png)

#### Phone Information:
Samsung Galaxy S8 SM-G950U
Android 9

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

#### Things I have tried:
- Using different image
- Using smaller image & larger image
- Different image types (jpg and png)
- Different aspect ratios

Is it possible I have somehow tagged the files wrong? Given that the image shows up fine in other apps, I'm not sure that could be the case, but I am open to suggestions. Thank you very much in advance for your help.

**Comment by OxygenCobalt** [comment] 2021-10-09 14:47
Hm. Another strange issue from Samsung's `MediaStore` flavor. 

Can you make sure that the "Show Covers" setting is on in the settings menu?
If it is on, then see if anything happens if you turn on the "Ignore MediaStore Covers" setting.

If both of these fail, then I will need a sample file to see if I can reproduce it on my device.

**Comment by OxygenCobalt** [comment] 2021-10-09 14:58
I say this because the file works fine on my device and seems to be pretty well-formed ID3v2 metadata.

![Screenshot_20211009-085321](https://user-images.githubusercontent.com/65370175/136663280-c419fc94-4951-4406-8dbd-285fc27aceb9.png)

So this is either:
1. Covers being off in Auxio
2. Samsung's `MediaStore` being annoying again.

**Comment by OxygenCobalt** [comment] 2021-10-09 15:26
> VLC, Vanilla

Expected, they don't rely on MediaStore

> Metro

Now *thats* strange. I'll drop by their repo and see what they do, because as I said they might be querying last.fm for covers when that setting is on.

**Comment by nswerhun** [comment] 2021-10-09 15:31
> ... they might be querying last.fm for covers when that setting is on.

These files I have tagged myself with my own image. It is often not the "official" album cover. That is the case with the file I provided; it was a pretty picture I found on Google which I thought went well with the music. I don't think they could be getting it from last.fm.

**Comment by OxygenCobalt** [comment] 2021-10-12 18:16
Can you try out this test APK? I've made the change.

Some things to know before trying this out:
- You will have to rename this file to .apk to install it
- This build has the new 2.0.0 design I've been working on, the settings will be in the overflow menu at the top.
- "Ignore MediaStore Covers" needs to be turned on settings, otherwise the cover art will optimize for speed and try to use the android-generated covers [Which in your case won't work]
- I could only get it to work with ID3v2 and FLAC metadata, as those are the only formats ExoPlayer can internally fetch pictures from.
- The ExoPlayer parser is slower and doesn't cache as easily. However, since it's a fallback this is tolerable.

[Auxio_BetterCovers.zip](https://github.com/OxygenCobalt/Auxio/files/7332289/Auxio_BetterCovers.zip)

**Comment by OxygenCobalt** [comment] 2021-11-18 17:42
Re-opening since it turns out that my exoplayer solution results in a blocking call and breaks the coil loading process. I have no idea how to fix this.

**Closed** 2021-11-21 14:35 UTC
Labels: bug

**Comment by Tom4tot** [comment] 2024-02-05 11:40
Hi. Just switched to Galaxy S24 and I'm facing the exact same issue. I think it did work at some point for some albums but it doesn't anymore. Fun fact, it makes the app much smoother (so your explanation was indeed accurate: https://github.com/OxygenCobalt/Auxio/issues/579#issuecomment-1729626713 ).

If you have any ideas I'll be happy to test them. Currently, my covers are not embedded in files but in the same folders as a .jpg file. Would it help to embed them?
