### ISSUE TITLE
Link album artists to all songs in an album

### ISSUE THREAD

**Issue by robertoprubio** [OxygenCobalt/Auxio#365] opened 2023-02-19 16:34 UTC
### Describe the Bug/Crash

Open the app
Go to artist
Some albums have no songs but the songs are enumerated when access to the album (see Alaska at artists list on the screenshots)

### Describe the intended behavior

The number of artist songs will be enumerated 

### What android version do you use?

Android 12

### What device model do you use?

Huawei P30
![IMG_20230219_172824_699](https://user-images.githubusercontent.com/31618496/219961412-8234fcf1-eb06-48d2-810d-16c6bc56ca78.jpg)
![IMG_20230219_172824_016](https://user-images.githubusercontent.com/31618496/219961415-2a4953f8-bac1-4242-ac90-931013b45296.jpg)
![IMG_20230219_172824_837](https://user-images.githubusercontent.com/31618496/219961416-616b68f1-dc39-4396-800d-63f0ffedddbc.jpg)
 

### Relevant log output

```shell
No logs
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-02-19 17:29
This is caused by having an artist name that is only in the "album artist" tag. The artists end up being only linked to albums. This is intentional behavior and can be fixed by adding "artist" tags to your music.

**Comment by robertoprubio** [comment] 2023-02-19 17:35
For all the 4 songs for this artist I have set the "album artist" and also the "artist".
The "artists" tab is listing the "album artist" for this artist ("Alaska" in this case) but not counting the songs.
The "artist" is "Alaska y los pegamoides" that is not listed at the "artists" tab. 


![Sin nombre](https://user-images.githubusercontent.com/31618496/219964826-671c5ad6-72be-456c-ae32-137400f1fbcf.png)

**Comment by OxygenCobalt** [comment] 2023-02-19 17:41
You do not want to structure your tags like that. If you hard-code collaborator information with a non-standard separator ("Alaska **y** dinarama"), Auxio will interpret them as separate artists. Alongside this, "Alaska y dinarama" will be considered a collaborator and be hidden from the library if "hide collaborators" is turned on.

I'd recommend something like this:
1. Retag anything like "Alaska y dinarama" to something like "Alaska + Dinarama".
2. Go to Settings -> Content -> Multi-value separators
3. Enable the "Plus" character option and press "Save".

This will allow Auxio to link those songs to the "Alaska" artist.

**Comment by robertoprubio** [comment] 2023-02-19 18:06
"Alaska y dinarama" is a Spanish group and will be considered an artist in opposite to "Alaska" and "Dinarama" ("Dinarama" doesn't not exists by itself) 😉

**Comment by OxygenCobalt** [comment] 2023-02-19 18:10
So, if it's not a collaboration, what *is* it exactly? Is it like a Band?

**Comment by robertoprubio** [comment] 2023-02-19 18:14
Alaska is a Spanish singer. Initially she and her group were "Alaska y los pegamoides", then they changed to "Alaska y dinarama" and finally she became independent and became a soloist. On this album they go through the solo discography of "Alaska" and her songs with her group (it's the same as if a Mark Knopfler compilation album includes a song from his time in Dire Straits) . Maybe I am not explaining myself clearly. Not a major problem, in any case. Once enabled to show collaborators both "Alaska y dinarama" and "Alaska y los pegamoides" appear in the list of artists and that's fine.

**Comment by OxygenCobalt** [comment] 2023-02-19 18:24
Oh. That's a really interesting edge-case. Currently the current behavior of what I call "oprhaned album artists" is derived from something like "various artists", where it doesn't exactly make sense to link it to songs. I think I can change that behavior so that artists linked to an album via an "album artist" tag simply bring in all songs from that album, but I also have to make sure I don't run into other edge-cases with that.

Thanks for pointing this out, gotta plug [this article](https://dustri.org/b/horrible-edge-cases-to-consider-when-dealing-with-music.html) every time I get an issue like this :smile:.

**Comment by OxygenCobalt** [comment] 2023-02-20 01:05
Actually, no, I can't really do this. The alternative edge case is something like an album with an "album artist" that contributes to *some*, but not all of the album. That would end up bringing in songs that are not related to the artist. I really dislike that behavior, honestly.

Sorry about this. Definitely moments like these where I wish there were "refinements" for artist and album info. Sometimes something can have the "same" name while needing some useful context added to it.

**Closed by OxygenCobalt** 2023-02-20 01:05 UTC
Labels: bug, music
