### ISSUE TITLE
Grid view in "Albums" tab

### ISSUE THREAD

**Issue by MysterioABC** [OxygenCobalt/Auxio#672] opened 2024-01-14 08:58 UTC
### Description

"Grid view"option along with current "list view" in the "Album" tab would be nice addition for the app. It will make album cover properly visible and would change look of app in good way.

### Other implementations

I have used to use google music app back in old days and it was nicely implemented into that app.

### Benefit

Better visibility of album cover. Easy to find specific albums, songs from the big collection.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-01-14 16:04
Duplicate of #156. I don't add alternative visual styles since it's a slippery slope that causes more visual styles to be requested, splitting my attention across too many UI components.

**Closed by OxygenCobalt** 2024-01-14 16:04 UTC
Labels: enhancement
