### ISSUE TITLE
Please support browsing via bluetooth

### ISSUE THREAD

**Issue by bhe69** [OxygenCobalt/Auxio#486] opened 2023-06-23 21:23 UTC
### Description

Auxio can be remote controlled via bluetooth, e.g. from a car's stereo. The used Exoplayer supports AVRCP (Bluetooth profile) Version 1.6 which introduced file browsing allowing to remotely select songs to play. (While it's called file browsing, which I understand you don't support, it also includes Albums, Artists etc., see below)
Using this function would allow the user to browse the music stored on his/her mobile and add new music to the playlist via bluetooth. Currently bluetooth control only allows skipping the tracks in the playlist set up on the mobile phone.

It is documented here:
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaMetadata.FolderType.html

> FOLDER_TYPE_TITLES, FOLDER_TYPE_ALBUMS, FOLDER_TYPE_ARTISTS, FOLDER_TYPE_GENRES, FOLDER_TYPE_PLAYLISTS, FOLDER_TYPE_YEARS

### Other implementations

To my knowledge no other music player supports this yet. Some guy did some unsuccessful research here: https://android.stackexchange.com/questions/218823/why-is-google-play-music-the-only-app-that-produces-a-browse-button-on-my-car/

### Benefit

When we're listening to music in the car and controlling Auxio via bluetooth we can only play songs from the current playlist, skipping back and forth, but not selecting new songs from the library. Allowing "File" (actually: Genre, Album, Artist etc.) browsing via Bluetooth would solve this and make Auxio the only Android Music player to support this function..

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-06-23 21:40
Duplicate of #37, I believe. What I need to do is implement `MediaBrowserService`, which should have AVRCP requests forwarded to it. Sadly the playback service lifecycle is borked due to dumb architecture decisions I made early on, which I'm still working on.

**Closed by OxygenCobalt** 2023-06-23 21:40 UTC
Labels: enhancement

**Comment by bhe69** [comment] 2023-06-24 18:31
> Duplicate of #37, I believe. What I need to do is implement `MediaBrowserService`, which should have AVRCP requests forwarded to it. Sadly the playback service lifecycle is borked due to dumb architecture decisions I made early on, which blocks that change at the moment.

The issue #37 you linked is about Android Auto.

Just to clarify: I'm not talking about Android Auto, an extra app on your mobile which allows you to use and mirror certain apps to the head-unit in your car. I'm talking about the music player app control via bluetooth, which has typically the basic functions next song / previous song / play / pause etc.

**Comment by OxygenCobalt** [comment] 2023-06-24 18:41
Yes, and Android Auto and AVRCP likely communicate to the same interface (`MediaBrowserService`). I just need to implement that and AVRCP support should come with it @bhe69.
