### ISSUE TITLE
Duplicate album crash 

### ISSUE THREAD

**Issue by jf916** [OxygenCobalt/Auxio#475] opened 2023-06-07 17:10 UTC
### Describe the Bug/Crash

Album is duplicated and one of them works and the other crashes the app happened on stable v3.1.1 and latest canary build was fine on v3.1.0

### Describe the intended behavior

Should play the album

### What android version do you use?

Android 13

### What device model do you use?

Samsung Galaxy S10 (LineageOS 20)

### Bug report

[Video capture link](https://drive.google.com/file/d/1Zd49gp7PloJNvEa0Uud2tZXPP-Fue_sa/view?usp=drivesdk) is there

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by jf916** [comment] 2023-06-07 20:00
I did some checking and I used different canary versions and my notes are below

 0d28bdf has bug
 c2def19 is ok
 6fc7439 is ok
 f9ccb83 has bug
 46fb33d is ok
 f9ccb83 is the cause of the bug

**Comment by OxygenCobalt** [comment] 2023-06-07 20:49
Thanks for this, seems like the issue was caused by `rawArtists == other.rawArtists` becoming `other.rawArtists == other.rawArtists`. I'll fix this asap.

**Comment by OxygenCobalt** [comment] 2023-06-08 02:10
I've resolved the inequality issue. Could you try the new Canary APKs @jf916 and report to me if the issue is fixed?

**Comment by jf916** [comment] 2023-06-08 06:48
Ok I am just doing that

**Comment by jf916** [comment] 2023-06-08 06:54
The latest canary build ( 5ab46ba ) has still got the bug

**Comment by jf916** [comment] 2023-06-08 15:58
The link to the whole album is [Here](https://drive.google.com/drive/folders/1_P7tK3WHhx0RXSCSuoRH-M8Wf3MHJkFH)

**Comment by OxygenCobalt** [comment] 2023-06-09 02:45
Identified the issue, one of the songs in that album has a "sort artist" tag that existed in none of the other apps. Combined with a regression where Auxio would not ignore artist sort information when grouping albums, it resulted in two duplicate albums with the same UID. Will make a fix for this.

**Closed** 2023-06-09 02:48 UTC
Labels: bug, music

**Comment by jf916** [comment] 2023-06-09 06:45
Thank you for fixing it

**Comment by Jose14** [comment] 2023-06-09 15:51
Hello. Why is it not available on Play Store?

**Comment by OxygenCobalt** [comment] 2023-06-09 15:52
Because the Play Store is a proprietary and draconian platform that is complicit in the rampant stealing of free software. If you are instead asking why this fix is not available on F-Droid, I have not made a release with this fix yet @Jose14.
