### ISSUE TITLE
Unknown music loading failure since 3.1.2

### ISSUE THREAD

**Issue by SonicEraZoR** [OxygenCobalt/Auxio#495] opened 2023-06-30 06:05 UTC
### Describe the Bug/Crash

So this problem isn't actually new to me since I have a Python script that downloads my YouTube Music playlist setup in Termux and that error occurred after I downloaded some new songs with that script.

But before I was able to fix it with a combination of uninstalling Auxio, renaming my music folder, rebooting the phone and then installing it again.

Except with 3.1.3 that doesn't seem to work anymore (and even with previous 3.1.2 and 3.1.1 versions, 3.1.2 just hangs like in this issue #484 and 3.1.1 acts exactly the same as 3.1.3) so I'm kinda have no idea how to fix this anymore.

I'm not sure from which version of Auxio I upgraded since I don't remember which version it was, it was an automatic update from F-Droid.

### Describe the intended behavior

Music library should load and it shouldn't give "Error reading library" message

### What android version do you use?

Android 12

### What device model do you use?

POCO M3 Pro (Lineage OS 19.1 GSI)

### Bug report

![screenshot-2023-06-30-12-45-58-2](https://github.com/OxygenCobalt/Auxio/assets/33545675/2acd61c3-8d10-4716-ade8-79b16cf9f236)

[Bug report zip](https://drive.google.com/file/d/1ebDbKGGhTngn04Tbg3oH3J6EWxRJbhZn/view?usp=drivesdk)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-06-30 14:30
Sadly, it seems like your phones system log is broken, so I can't obtain that information normally. I'll need to make some kind of debug dialog that actually shows the stack trace.

**Comment by SonicEraZoR** [comment] 2023-07-01 03:11
Might be a GSI thing, it's not exactly the most stable type of ROM, it's just there is no other custom ROMs for my phone

**Comment by SonicEraZoR** [comment] 2023-07-01 05:38
Also I can technically reflash it back to MIUI if necessary

**Comment by OxygenCobalt** [comment] 2023-07-02 16:26
Something you can do in the mean-time @SonicEraZoR is selectively add/remove files from your device until the error disappears. That way, you can actually share a file that I can use to reproduce the issue on my device.

**Comment by SonicEraZoR** [comment] 2023-07-03 05:22
> Something you can do in the mean-time @SonicEraZoR is selectively add/remove files from your device until the error disappears. That way, you can actually share a file that I can use to reproduce the issue on my device.

Uhhhhh yeah funny story, I tried to do that and it suddenly just worked....? Right now all of my music is loaded properly

**Comment by SonicEraZoR** [comment] 2023-07-03 05:56
You know, I actually deleted the music with CX Explorer and it has Recycle Bin feature, so I deleted chunks of music into a recycle bin until nothing was left, because error was still occurring, then I restored all the music from the recycle bin and the error was still there. But then I deleted a chunk of music again and it worked, and then I restored everything I deleted and... it still worked. And now I'm here. So I'm thinking maybe CX Explorer recycle bin somehow fixed whatever was broken with the files...?

**Comment by OxygenCobalt** [comment] 2023-07-03 15:40
That's really weird. If it re-appears again please let me know.

**Comment by SonicEraZoR** [comment] 2023-07-03 17:31
Will do

**Comment by s0m3sushi** [comment] 2023-07-26 13:21
I also had this problem when I just downloaded an album, I managed to fix it by disabling Intelligent sorting.

**Comment by OxygenCobalt** [comment] 2023-07-26 15:16
That's an edge case I'm not handling, could you provide a bug report in a new issue @s0m3sushi?

**Comment by s0m3sushi** [comment] 2023-07-27 01:30
The custom ROM I'm using doesn't seem to have a bug report feature, so I'll give a sample file that caused the issue. I'm running on a Redmi Note 7 on PixelExperience 13 btw.
[13_Controlled_Depopulation.mp3.zip](https://github.com/OxygenCobalt/Auxio/files/12178533/13_Controlled_Depopulation.mp3.zip)

**Comment by s0m3sushi** [comment] 2023-07-27 01:37
Looks like it wasn't the file thats causing the issue, I have a lot of albums loaded onto Auxio and this one album managed to break it for some reason. But when I try to include only the album from the song mentioned above, it loads up just fine.

**Comment by OxygenCobalt** [comment] 2023-07-27 01:40
Ugh... You'll need to wait then, I really need to add some kind of stack trace accessible in-app.

**Comment by OxygenCobalt** [comment] 2023-08-15 01:46
Closing this since there's no clear resolution. Guess I'll wait for the next person to encounter this issue.

**Closed by OxygenCobalt** 2023-08-15 01:46 UTC
Labels: bug, music
