### ISSUE TITLE
[Feature Request] Playlist support

### ISSUE THREAD

**Issue by cyclonejet** [OxygenCobalt/Auxio#61] opened 2021-12-26 22:59 UTC
#### Describe the feature you want to implement:
Create playlists, save them to .m3u file and read playlists from .m3u files.

#### Is your feature request related to a problem? Please describe:
No, but I'd like to listen to specific songs from my playlist.

#### Why do you think this will improve everyone's usage of Auxio?
So that everyone can start making playlists and shuffle/loop those songs only without having to skip songs.

#### Due Diligence:

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2021-12-26 23:01
Dupe of #36. I'm still planning this, but the implementation will have m3u importing/exporting while the actual way the playlists are stored is through an internal database.

**Closed by OxygenCobalt** 2021-12-26 23:01 UTC
Labels: enhancement

**Comment by cyclonejet** [comment] 2021-12-26 23:03
Sorry, I did check the issues but must have missed. Thanks for fast response and a fast music app.
