### ISSUE TITLE
Add a fast and Reverb and slowed option

### ISSUE THREAD

**Issue by Nathan1887** [OxygenCobalt/Auxio#910] opened 2024-11-10 02:02 UTC
### Description

I want you to add the option to change the speed and the reverb. So I can make my song slowed and reverb and sped up. There is an option to do it manually or automatically per song

### Problem solved

Like Its quite a hassle when downloading slowed and reverb and sped up songs from online. 

### Other implementations

This music player is good, and the design is good. I was using the vanilla music player but it isn't on the Google play store anymore and that i cant access their website and some of my songs isn't shown so I tried something new until i saw auxio on the F-droid

### Benefit

This feature will be a time saver because you dont need to download sped up and slowed and reverb from online which is a hassle. And this will benefit if a user keeps listening and wants something new with the music. (Sorry if my English is bad 😅)

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-11-11 16:52
Duplicate of #814/#146. Reverb can be done with an equalizer like Wavelet and would be better served there, and I don't personally gain any benefit from speed control, which means the feature would rot over time as I won't be regularly testing it. Sorry.

**Closed by OxygenCobalt** 2024-11-11 16:52 UTC
Labels: enhancement
