### ISSUE TITLE
Feature request regarding visualisations

### ISSUE THREAD

**Issue by Lucky390163** [OxygenCobalt/Auxio#786] opened 2024-06-02 16:55 UTC
### Description

1) Please add an option to enable or disable the small bsrs of visualisations.But it is using battery in comparison to other apps.Humble Request.
2) Please add recently added,most played, and favorite tabs.App is looking uncomplete without it.

### Problem solved

No

### Other implementations

Other players can handle it very easily.

### Benefit

It will improve user experience

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-06-02 18:27
Visualizations currently require additional permissions and are not easily integrated into a crammed playback UI that can't fit much else.

I've already rejected most played, it's extremely difficult to implement internally and is too much for something that isn't used much by me and others. 

As for recently added, you can just sort by date added. Signifigantly less cluttered than a random tab.

Favorites is a duplicate of a prior issue.

**Closed by OxygenCobalt** 2024-06-02 18:27 UTC
Labels: enhancement
