### ISSUE TITLE
Can a mini player overlay be used to play files directly?

### ISSUE THREAD

**Issue by alexceltare2** [OxygenCobalt/Auxio#790] opened 2024-06-03 16:29 UTC
### Description

When I open a .mp3 or .wav file with my File Manager, I want just a tiny player to popup just like other music players, not the entire app.

### Other implementations

Small miniplayer is popped up

### Benefit

Less clutter and easy management of audio files.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-06-05 04:51
Duplicate of prior issues. This isn't technically feasible right now since songs can't exist independently of the music library and there's no good way to "upgrade" a standalone playback song if you do actually start the app. Sorry.

**Closed** 2024-06-05 04:51 UTC
Labels: enhancement
