### ISSUE TITLE
External equalizer (i.e Wavelet) support

### ISSUE THREAD

**Issue by lunandd** [OxygenCobalt/Auxio#211] opened 2022-08-08 16:23 UTC
#### Describe the feature you want to implement:
Adding support for external equalizers i.e [Wavelet](https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet&hl=en_US&gl=US).

#### Why do you think this will improve everyone's usage of Auxio?
Adding support for external equalizers would allow us to optimize our listening experience. For example, Wavelet would allow us to use an Equalizer/AutoEq optimized for specific models of headphones and many other effects that it offers such as a Limiter and a Bass tuner.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment] 2022-08-08 22:19
Huh. Never knew Wavelet existed. Seems like I have to do some weird broadcast thing with `AudioEffect` to enable it. This actually seems like a much more feasible solution than trying to do an equalizer internally, I'll look into it.

**Comment by OxygenCobalt** [comment] 2022-08-09 04:18
@mariobrostech Just to let you know, I've now accepted your request. Now that I am aware of Wavelet, delegating the equalizer to an external implementation is actually quite good and follows the unix-esque philosophy I try to follow with this app.

Currently, this is blocked by the technical issues. It requires me to do this weird dance with broadcasting special `Intent` instances that not all devices support. However, I can't really leverage open-source implementations of such like Phonograph, as they seem to not fully implement this correctly (Some equalization options in Wavelet are disabled for whatever reason).

Since Wavelet itself is closed-source, I might try to e-mail the author for more help on getting my app working well with Wavelet using the `AudioEffect` API. Definitely blocked right now, as #174 is my priority.

**Comment by lunandd** [comment] 2022-08-09 08:35
> @mariobrostech Just to let you know, I've now accepted your request. Now that I am aware of Wavelet, delegating the equalizer to an external implementation is actually quite good and follows the unix-esque philosophy I try to follow with this app.
> 
> Currently, this is blocked by the technical issues. It requires me to do this weird dance with broadcasting special `Intent` instances that not all devices support. However, I can't really leverage open-source implementations of such like Phonograph, as they seem to not fully implement this correctly (Some equalization options in Wavelet are disabled for whatever reason).
> 
> Since Wavelet itself is closed-source, I might try to e-mail the author for more help on getting my app working well with Wavelet using the `AudioEffect` API. Definitely blocked right now, as #174 is my priority.

After some searching, I found this [comment](https://github.com/Pittvandewitt/Wavelet/issues/32#issuecomment-691476597) on an issue from the author of Wavelet which many help you implement Wavelet support later on

**Comment by OxygenCobalt** [comment] 2022-08-09 14:38
Okay, that seems clearer now. AFAIK this is maybe a 3-line change, but then I have to add some equalizer shortcut in the UI which is a bit harder.

**Comment by OxygenCobalt** [comment] 2022-08-09 15:29
Okay @lunandd, does this APK work (Rename it from ZIP)? Auxio now opens an equalizer session when the service starts and closes it when the service dies. 

[Auxio_Equalizer.zip](https://github.com/OxygenCobalt/Auxio/files/9292396/Auxio_Equalizer.zip)

**Comment by OxygenCobalt** [comment] 2022-08-09 15:56
Never mind, that build doesn't work. Apparently Wavelet doesn't like you broadcasting an AudioEffect session without any music loaded into the player first.

**Comment by lunandd** [comment] 2022-08-09 15:58
> Never mind, that build doesn't work. Apparently Wavelet doesn't like you broadcasting an AudioEffect session without any music loaded into the player first.

Yep, I was just going to reply saying it doesn't work

**Comment by OxygenCobalt** [comment] 2022-08-09 16:04
Okay, this is the *new* APK that correctly broadcasts the audio effect. I open a session when I'm loading/playing a music file, and then I close it when the service dies. I'll see if I can the implementation up later:

[Auxio_Equalizer2.zip](https://github.com/OxygenCobalt/Auxio/files/9292763/Auxio_Equalizer2.zip)

**Comment by lunandd** [comment] 2022-08-09 16:07
This one works and all the effects too!

**Comment by lunandd** [comment] 2022-08-09 16:08
> Okay, this is the *new* APK that correctly broadcasts the audio effect. I open a session when I'm loading/playing a music file, and then I close it when the service dies. I'll see if I can the implementation up later:
> 
> [Auxio_Equalizer2.zip](https://github.com/OxygenCobalt/Auxio/files/9292763/Auxio_Equalizer2.zip)

This one works and all the effects too!

**Comment by OxygenCobalt** [comment] 2022-08-09 22:16
Great. Yeah, the "null" app value is kind-of weird. Might be either the debug build or ExoPlayer being finicky.

**Closed** 2022-08-09 22:26 UTC
Labels: enhancement, playback

**Comment by OxygenCobalt** [comment] 2022-08-09 22:58
This should arrive in 2.6.1. Note that a button for *opening* the equalizer will take more time, as for perfectionist UI reasons it is blocked by #93.

**Comment by Pittvandewitt** [comment] 2022-08-17 09:11
> Great. However, the "null" app value is kind-of weird though. I can reproduce it on my app too. Might be either the debug build or ExoPlayer being finicky.

A step in the right direction can be found here: https://developer.android.com/guide/topics/media-apps/audio-app/building-a-mediabrowserservice
I haven't looked too much into it, but maybe only adding the intent filter could do the job.

**Comment by OxygenCobalt** [comment] 2022-08-19 00:53
Okay. Probably can't do the intent filter right now though since it derails #37. Don't want car users to be confused why there is an "Auxio" entry that is unusable since I just added the intent filter.

**Comment by Pittvandewitt** [comment] 2023-06-23 09:11
> Great. However, the "null" app value is kind-of weird though. I can reproduce it on my app too. Might be either the debug build or ExoPlayer being finicky.

The cause of the null value is because Wavelet is unable to query the package details of Auxio because the MediaBrowserService intent filter is missing. If you add
```
<intent-filter>
    <action android:name="android.media.browse.MediaBrowserService" />
</intent-filter>
``` 
to your service entry in your manifest, the issue will be resolved.

See [https://developer.android.com/guide/topics/media-apps/audio-app/building-a-mediabrowserservice](https://developer.android.com/guide/topics/media-apps/audio-app/building-a-mediabrowserservice) for details

**Comment by OxygenCobalt** [comment] 2023-06-23 18:48
I know @Pittvandewitt. I can't really do that at the moment, since it would then lead to android auto thinking that Auxio could be opened, but the service wouldn't actually handle any of the requests required. That's a really bad user-experience compared to leaving it `null` until I can do #37.
