### ISSUE TITLE
Music loading failed

### ISSUE THREAD

**Issue by fmontalvoo** [OxygenCobalt/Auxio#679] opened 2024-01-16 22:36 UTC
When I launch the application it shows the following error message:

android.database.sqlite.SQLiteException: near "OR": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id, date_added, date_modified, _size, duration, mime_type, title, year, album, album_id, artist, album_artist, _display_name, volume_name, relative_path, cd_track_number, disc_number FROM audio WHERE ((((is_pending=0 AND NOT _modifier=4) OR (is_pending=1 AND lower(_data) NOT REGEXP '.*/\.pending-(\d+)-([^/]+)$' AND owner_package_name IN ( 'org.oxycblt.auxio' )))) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' , '0123-4567' ))) AND (NOT _size=0 AND is_music=1 AND  ( OR (volume_name LIKE ? AND relative_path LIKE ?)))
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1219)
	at android.content.ContentResolver.query(ContentResolver.java:1151)
	at android.content.ContentResolver.query(ContentResolver.java:1107)
	at org.oxycblt.auxio.music.fs.StorageUtilKt.safeQuery(Unknown Source:6)
	at org.oxycblt.auxio.music.fs.MediaStoreExtractorImpl.query(SourceFile:369)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreQueryJob$1.invokeSuspend(SourceFile:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.fragment.app.Fragment$4.run(SourceFile:43)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

**Comment by OxygenCobalt** [comment] 2024-01-16 22:36
Duplicate of #667

**Closed by OxygenCobalt** 2024-01-16 22:36 UTC

**Comment by dmint789** [comment] 2024-01-17 20:24
@OxygenCobalt could you please release 3.3.3 on F-droid?

**Comment by OxygenCobalt** [comment] 2024-01-18 03:46
I have no control over F-Droid releases, and F-Droid won't push the new version for probably a week @dmint789. Even if I manually PR the new version in, it will still build it alongside all of the other apps.

**Comment by dmint789** [comment] 2024-01-18 07:10
Oh, I see. I'll wait then.
