### ISSUE TITLE
Option to hide "Unknown genre"

### ISSUE THREAD

**Issue by leandroprz** [OxygenCobalt/Auxio#736] opened 2024-03-03 16:51 UTC
### Description

I think it would be great to have an option to hide the "Unknown genre" when when in the Genres tab.

### Other implementations

An option to hide certain genres or just the unknown genre.

### Benefit

I usually only tag my Soundtracks genre field, so it would be nice to just see that and not everything that says "unknown".

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-03-06 01:21
Duplicate of #99. I generally don't like the complexity of this functionality, especially when the solution seems to be more obviously to just tag the music. There are tools that'll do that automatically like [beets](https://github.com/beetbox/beets) with the lastfm genre plugin.

**Closed by OxygenCobalt** 2024-03-06 01:21 UTC
Labels: enhancement

**Comment by illdeletethis** [comment] 2024-03-06 16:24
normally i"d agree with tagging everything properly, but quite regularly albums have short intro, outro, interlude snippets that just don"t deserve the effort of finding the correct genre for, or even a compromise that avoids spamming the genre list with a huge variety of otherwise not listened to genres, which is quite different from the usual genre of that band.
in that case i"d quite like being able to keep the field empty and the track hidden from the genre tab as well.
