### ISSUE TITLE
[Request] Add folders tab

### ISSUE THREAD

**Issue by Guuustav** [OxygenCobalt/Auxio#456] opened 2023-05-26 12:55 UTC
Great job @oxygencobalt The player is excellent and my favorite ever since I discovered it. I would like to make a request. Would it be possible to add the folder tab in the tab bar (Songs, Albums, Artists...). 

This suggestion is because in my music folder I already have a classification in 4 subfolders, which I always use to import them individually to create 4 playlists. Auxio mixes the music from the 4 folders and for me it would be perfect to add this option. 

Thanks in advance.

**Comment by OxygenCobalt** [comment] 2023-05-26 15:42
This is a duplicate of countless prior issues. Auxio is not a folder-based music player, as the UI of such is completely different from a tag-based music player. It would only result in a mediocre folder view and take time away from other functionality. This will never be added.

**Closed by OxygenCobalt** 2023-05-26 15:42 UTC
