### ISSUE TITLE
Lyrics Support 

### ISSUE THREAD

**Issue by Raif1** [OxygenCobalt/Auxio#86] opened 2022-02-27 13:53 UTC
#### Describe the feature you want to implement:

Lyrics Support . And it marks the lyrics when its being said 

#### Is your feature request related to a problem? Please describe:

No 
#### Do other music players handle this? If so, how?

Spotify handles this amaizingly. Spotify marks the lyrics when they are being said . Whick looks real cool. 

#### Why do you think this will improve everyone's usage of Auxio?

Its a basic thing which every music player needs. And makes it more attractive etc.......

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment] 2022-02-27 13:55
Duplicate of #48, #33, and #19. I do not benefit from lyrics as most of my music is instrumental.

**Closed by OxygenCobalt** 2022-02-27 13:55 UTC
Labels: enhancement
