### ISSUE TITLE
Artist and albums splitting for no reason.

### ISSUE THREAD

**Issue by sgreenden** [OxygenCobalt/Auxio#835] opened 2024-07-19 18:52 UTC
### Describe the Bug/Crash

In Auxio, I have one big issue, that being releases are often split into different artist categories, even if they have the exact name, and also different albums, even if they have the exact same album, album artist, artist and date tags. I tested in another music player and the issue didn't pop up there. 
![Screenshot_20240719_142432_Auxio](https://github.com/user-attachments/assets/2bd12e8d-42e1-4969-ac81-061ba53c44f1)
Here are the four different splits
![Screenshot_20240719_142440_Auxio](https://github.com/user-attachments/assets/e644b3ab-ac60-4d76-b38a-6276443f7e12)
![Screenshot_20240719_142450_Auxio](https://github.com/user-attachments/assets/f9fab993-2531-4df5-981b-d11fbdef325d)
![Screenshot_20240719_142459_Auxio](https://github.com/user-attachments/assets/9a4faaac-c5eb-4760-bb22-edc0498de2b1)
![Screenshot_20240719_142509_Auxio](https://github.com/user-attachments/assets/78557f9a-1fe4-4c25-8f76-9e9b8232c206)
This is what's in them.
![Screenshot_20240719_143644_Auxio](https://github.com/user-attachments/assets/90c6191f-a67e-45ed-8209-ad7426c2c8dd)
One is even under a different category of the same artist for some reason.
![Screenshot_20240719_143655_Auxio](https://github.com/user-attachments/assets/04bb9efb-da65-40f1-933e-c6b5f43ffd10)
![Screenshot_20240719_143743_Auxio](https://github.com/user-attachments/assets/42ecad33-9622-488c-bf59-d880c62cfc50)
![Screenshot_20240719_143820_Auxio](https://github.com/user-attachments/assets/96f20884-43ab-4a77-8b56-41f18e038592)
![Screenshot_20240719_143843_Auxio](https://github.com/user-attachments/assets/5aead11a-5b1a-4e44-b403-e0542bdb9315)
![Screenshot_20240719_143915_Auxio](https://github.com/user-attachments/assets/4b20eeee-a0c4-45fe-b048-0c706846e59f)
No discernable tag difference.

Here are some screenshots showing an example of this, but it happens with other albums and releases. I have it tagged correctly and it displays right in other software, I'm not sure what could be happening here. I notice sometimes this auxio ep tag appears above which only happens when a few random songs are pulled out of an album and separated. I usually have to make playlists As a work around. 
I notice on the 4 extra splits of the album that they're split on discs and also have the artist name repeated in parenthesis for some reason. The first one has multiple discs, and they're all tagged the same, so I'm not sure why those are singled out or why one is under a different artist.

### Describe the intended behavior

![Screenshot_20240719_144003_foobar2000](https://github.com/user-attachments/assets/0e4a0827-99ce-4b12-862a-04f85b4ad83b)
![Screenshot_20240719_153009_foobar2000](https://github.com/user-attachments/assets/cb0a57c7-890c-4b87-9ed1-18e059b2e21f)

In this other music player, it just displays things as they're tagged.

### What android version do you use?

Android 13

### What device model do you use?

Galaxy A13

### Provide a sample file

N/A

### Bug report

I don't think I have this feature.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-07-20 19:16
Duplicate of #555, for now you need to strip all MusicBrainz IDs or fully use MusicBrainz IDs in your library. Using an autotagger like MusicBrainz Picard or beets is easiest.

**Closed by OxygenCobalt** 2024-07-20 19:16 UTC
Labels: bug
