### ISSUE TITLE
Support read more directories

### ISSUE THREAD

**Issue by L2750558108** [OxygenCobalt/Auxio#870] opened 2024-09-15 04:36 UTC
### Description

For example, actively apply for permission to read audio under android/data; read audio under root directory in ROOT user.
If the permission request should not be active, you can add a "Scan Media" option, open a folder selector, and request the appropriate permissions based on the selected folder.
Additional, I've found that now if I try to use Auxio in the file manager to open music from a directory that it can't access, the program gets opened but just stays on the main page and does nothing. It can automatically open the Scan Media interface at this point

### Other implementations

I don't know how other audio players do it, some players don't need to apply for any permissions, some players don't support this

### Benefit

It supports audio playback on the entire device, and you can easily use Auxio to play audio in all paths

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-09-17 21:39
I think this is a duplicate of #322. I don't think I'll be doing anything related to ROOT support, since I can't see a use-case where someone is storing music in root folders.

**Closed by OxygenCobalt** 2024-09-17 21:39 UTC
Labels: enhancement
