### ISSUE TITLE
Scrolling causes app to freeze with large libraries

### ISSUE THREAD

**Issue by JulGvoz** [OxygenCobalt/Auxio#461] opened 2023-06-01 11:19 UTC
### Describe the Bug/Crash

1. Ensure that you have a very large amount of songs
I have 713 songs loaded, 63 albums, 54 artists, 3 genres and total duration of more than 49 hours.
2. Load the music tab
3. Try scrolling to interact with the music tab, swipe to scroll
4. Observe that UI is quite laggy, even on a powerful device. Furthermore, it is sometimes possible to see the placeholder thumbnails loading.

I believe it is because of the new icons displayed next to the song names, which are loaded when scrolling. 

Note that this is not a caching issue - even after scrolling through the entire list of music, the lag persists.

### Describe the intended behavior

No matter the number of songs, the UI should be responsive, i.e. not laggy.

### What android version do you use?

Android 12

### What device model do you use?

Galaxy S21 5G

### Bug report

Please contact privately at `github@julgvoz.com` for bug report

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-06-01 15:51
This is not something I can reproduce or debug by logs, so can you test the following debug APKs from 3.1.0 development?

From 89eeaa3: [Auxio_89eeaa3.zip](https://github.com/OxygenCobalt/Auxio/files/11627222/Auxio_89eeaa3.zip)
From 5fff1bd: [Auxio_5fff1bd.zip](https://github.com/OxygenCobalt/Auxio/files/11627225/Auxio_5fff1bd.zip)
From b2e899a: [Auxio_b2e899a.zip](https://github.com/OxygenCobalt/Auxio/files/11627228/Auxio_b2e899a.zip)

This way, I can bisect the issue. I actually doubt it's image related, as that should run asynchronously. It's probably an evil android quirk I didn't realize. Pinging @TheLastZombie since they also have this issue.

**Comment by TheLastZombie** [comment] 2023-06-01 16:52
The issue occurs with `89eeaa3`, but not `5fff1bd` and `b2e899a`.

**Comment by OxygenCobalt** [comment] 2023-06-01 17:06
Okay, how about these @TheLastZombie?

From 572b0e5: [Auxio_572b0e5.zip](https://github.com/OxygenCobalt/Auxio/files/11627821/Auxio_572b0e5.zip)
From fb89245: [Auxio_fb89245.zip](https://github.com/OxygenCobalt/Auxio/files/11627839/Auxio_fb89245.zip)

**Comment by OxygenCobalt** [comment] 2023-06-01 17:12
> In this version, some variant of the issue persists. When scrolling at a normal speed, lag does not exist or is not noticeable. When scrolling very quickly, it lags/freezes, but for shorter amount of time than in v3.1.0

The problem is that this issue scales quadratically. It's not bad for you (or me) since we have <1000 songs. It's much worse for people with 3k or more, it seems.

Anyway, here's one more APK from `049d2bc` @JulGvoz @TheLastZombie:
[Auxio_049d2bc.zip](https://github.com/OxygenCobalt/Auxio/files/11627876/Auxio_049d2bc.zip)

**Comment by OxygenCobalt** [comment] 2023-06-01 17:17
Can you try those other APKs [here](https://github.com/OxygenCobalt/Auxio/issues/461#issuecomment-1572447465) @JulGvoz?

**Comment by OxygenCobalt** [comment] 2023-06-01 17:25
Okay, I think I've narrowed it down to these two APKs now @JulGvoz @TheLastZombie:

From 1fd6795: [Auxio_1fd6795.zip](https://github.com/OxygenCobalt/Auxio/files/11627957/Auxio_1fd6795.zip)
From cee92c8: [Auxio_cee92c8.zip](https://github.com/OxygenCobalt/Auxio/files/11627958/Auxio_cee92c8.zip)

**Comment by JulGvoz** [comment] 2023-06-01 17:26
1fd6795 - issue persists

**Comment by OxygenCobalt** [comment] 2023-06-01 17:36
Finally! Sadly that commit is huge and I'll need to spitball the causes now.

> I find `computeAlbumOrdering` to be suspicious - it seems to be doing sorting now first? In `app/src/main/java/org/oxycblt/auxio/image/extractor/CoverExtractor.kt` 

If it was the culprit, it should have caused issues prior.

The thing that sticks out to me is the back navigation system polling every frame, perhaps that commit was the final straw. In that case, try this APK from an in-dev commit that changed that behavior:
From `5d51adf`: [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11628011/Auxio_Canary.zip), which broke it up into sub-listeners that might be less expensive

I'll keep replying with possible fixed APKs, just keep testing @JulGvoz @TheLastZombie

**Comment by JulGvoz** [comment] 2023-06-01 17:38
5d51adf - issue persists

**Comment by OxygenCobalt** [comment] 2023-06-01 17:41
Okay, I'll entertain the image problem and remove that code @JulGvoz: [Auxio_Img.zip](https://github.com/OxygenCobalt/Auxio/files/11628064/Auxio_Img.zip)

**Comment by JulGvoz** [comment] 2023-06-01 17:42
> Okay, I'll entertain the image problem and remove that code @JulGvoz: [Auxio_Img.zip](https://github.com/OxygenCobalt/Auxio/files/11628064/Auxio_Img.zip)

Issue **does not** persist

**Comment by OxygenCobalt** [comment] 2023-06-01 17:51
Ugh, you were actually right. I really thought that Coil keyed on a co-routine, but apparently not. I'm going to need to optimize that routine a bit @JulGvoz.

**Comment by JulGvoz** [comment] 2023-06-01 17:53
I really appreciate you taking the time looking into this!

**Comment by OxygenCobalt** [comment] 2023-06-01 18:15
Can you try this APK @JulGvoz? I tried my best to optimize the routine: 
[Auxio_Img2.zip](https://github.com/OxygenCobalt/Auxio/files/11628258/Auxio_Img2.zip)

**Comment by OxygenCobalt** [comment] 2023-06-01 18:24
Oh, in that case, try this one @JulGvoz (I reverted the broken toolbars): 
[Auxio_Img3.zip](https://github.com/OxygenCobalt/Auxio/files/11628309/Auxio_Img3.zip)

**Comment by OxygenCobalt** [comment] 2023-06-01 18:27
Okay, this is great. @TheLastZombie If you can test eventually that would be great, as you have a significantly worse problem.

**Comment by TheLastZombie** [comment] 2023-06-01 18:41
Auxio_Img3 works great, thanks!

**Comment by OxygenCobalt** [comment] 2023-06-01 18:44
Okay, great! I think I can close this issue now.

**Closed by OxygenCobalt** 2023-06-01 18:44 UTC
Labels: bug, music

**Comment by OxygenCobalt** [comment] 2023-06-02 02:54
I actually just have one more APK @TheLastZombie @JulGvoz. I realized that the music comparison function doesn't compare everything, so I changed it so that it would actually do that. This probably won't re-introduce the issue, but just in case, can you make sure there isn't an issue with it?

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11631386/Auxio_Canary.zip)

**Comment by TheLastZombie** [comment] 2023-06-02 04:08
No issues here.
