### ISSUE TITLE
Add a sleep timer

### ISSUE THREAD

**Issue by Richard38907** [OxygenCobalt/Auxio#843] opened 2024-07-29 14:10 UTC
### Description

Sleep timer to end the music after a delay

### Other implementations

![Screenshot_20240729-160905_InnerTune](https://github.com/user-attachments/assets/886f72db-199b-408c-ba49-dcac35310b04)

### Benefit

To reduce battery usage and distraction when sleeping

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-07-29 23:50
Duplicate of prior issues.

In general since I don't use sleep timers I can't effectively maintain complex functionality like this without it breaking (or it breaking something else) over time. Sorry.

**Closed by OxygenCobalt** 2024-07-29 23:50 UTC
Labels: enhancement
