### ISSUE TITLE
Material design 3

### ISSUE THREAD

**Issue by Maha-Rajan** [OxygenCobalt/Auxio#678] opened 2024-01-15 21:19 UTC
### Description

I would like to see more md3 elements in the ui implementation. The pause/play can shift between the hexagonal button while playing and a round button while paused. The music scrubber can be the same as wiggly lines used by the system. And player screen ui colour to change according to album art colors.

### Problem solved

Consistency of upgrading elements to md3

### Other implementations

Another open source app called gramophone does this in it's ui

### Benefit

Just a visual improvement tbh but a small addition to making the ui more beautiful 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-01-15 22:02
- The Hexagon button is extremely difficult to implement, and is inconsistent with the rest of the Android OS media player, and the MD3 media player examples.
- Duplicate of #130.
- Duplicate of #616.

**Closed by OxygenCobalt** 2024-01-15 22:02 UTC
Labels: enhancement
