### ISSUE TITLE
Give reasons in error message when importing a playlist fails

### ISSUE THREAD

**Issue by edwinst** [OxygenCobalt/Auxio#744] opened 2024-03-23 13:48 UTC
### Description

The app current gives a very general message like "playlist could not be imported" if there are any problems when importing a playlist. It would help a lot with troubleshooting if the app gave the reason why the playlist could not be imported. By trial and error I found the following problems in my playlist files:

- playlist uses absolute paths that do not exist on the phone
- playlist uses correct relative paths but at least one of the audio files does not exist on the phone
- playlist is missing some or all "#EXTINF:" lines (I thought they were optional, but if they aren't, a specific error message would be great)
- playlist has Mac-style line-ends (only \r from iTunes export instead of \n or \r\n) (I don't know if this alone caused the import to fail or if it was a combination with the above)

### Problem solved

The problem is that currently the user has to guess what is wrong with a playlist file if the import fails.

### Other implementations

I don't think other implementations are relevant here, as the details of the error messages really depend on the Auxio import code.

### Benefit

Giving reasons in the error message speeds up troubleshooting, improves user experience, and reduces need for user support.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-03-23 17:02
This is kind of a duplicate of #739. The issue is that this requires a more complicated indicator (i.e a Snackbar), which means another view component I have to cram into the main UI. This is frustrating since I have no clue what will actually happen. Merging and adding this to the issue.

**Closed by OxygenCobalt** 2024-03-23 17:02 UTC
Labels: enhancement
