### ISSUE TITLE
ability to go back just few seconds

### ISSUE THREAD

**Issue by elEthamin** [OxygenCobalt/Auxio#725] opened 2024-02-25 17:11 UTC
### Description

I've been using auxio for a while and I love it. I love it. Well done.
However, one feature is missing on a daily basis. Being able to go back a few seconds or forward a few seconds. A -10s, +10s button.
please add it
thanks a million

### Other implementations

double tap or button

### Benefit

you've misheard a passage or you'd like to skip a small part, going backwards or forwards by a few seconds is handy.
taking the slider with your big finger is not precise. 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-02-25 17:21
Duplicate of #281. This has been on the backburner for awhile now, but I can work on it sooner if you become a sponsor and prioritize that issue.

**Closed** 2024-02-25 17:28 UTC
Labels: enhancement
