### ISSUE TITLE
Track cover is displayed wrong

### ISSUE THREAD

**Issue by steam3d** [OxygenCobalt/Auxio#808] opened 2024-06-21 13:44 UTC
### Describe the Bug/Crash

If each track has own cover and the same album name, the Auxio uses the first cover for all tracks instead of using an individual track cover. I tried to enable option hight quality cover, it did not help.

![image](https://github.com/OxygenCobalt/Auxio/assets/30986874/d05621d3-c5a0-4e45-97c7-34e6966b6450)

Each track on screenshot have own cover.

![image](https://github.com/OxygenCobalt/Auxio/assets/30986874/58f11fb2-60cd-4777-a3be-b35cc4a92006)

### Describe the intended behavior

The Auxio will display an individual cover of each track if the cover exists, like PowerAMP does.

### What android version do you use?

Android 14

### What device model do you use?

Samsung Galaxy Fold 4

### Provide a sample file

Issue is not related with playback

### Bug report

Issue is not related with application operation

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-06-21 14:00
I need sample files @steam3d

**Comment by steam3d** [comment] 2024-06-21 14:05
@OxygenCobalt 
https://www.dropbox.com/t/FNQnxmcbowduQcTn

**Comment by OxygenCobalt** [comment] 2024-06-21 18:18
Okay, this a duplicate of per-song album covers, which was added in 3.5.0 @steam3d. That version will be on f-droid shortly.

**Closed** 2024-06-21 18:18 UTC
Labels: bug
