### ISSUE TITLE
Certain artists are improperly separated

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#305] opened 2022-12-31 09:25 UTC
### Describe the Bug/Crash

see screenshot:
![Screenshot_20221231-093403_Auxio](https://user-images.githubusercontent.com/21956756/210131691-c669f669-8520-40e4-ad0e-30639b725106.png)
they both even have the same genre, some songs are in the first entry and others are in the second entry

### Describe the intended behavior

should show up in 1 artist, as it does in 2.6.4

### What android version do you use?

Android 12

### What device model do you use?

Galaxy M21 (oneui 4.1)

### Relevant log output

```shell
-
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2022-12-31 14:26
Do you use MusicBrainz IDs at all? If artists have different MBIDs, they will appear as separate entries. If you don't, it's a bug with the artist grouping system and I'll need sample files.

**Comment by KraXen72** [comment] 2022-12-31 16:00
i haven't ever heard of music brain id tags till now, but maybe they are added by deemix.

**Comment by KraXen72** [comment] 2022-12-31 16:00
i can send sample files but idk when because im not on wifi.

**Comment by KraXen72** [comment] 2022-12-31 16:01
how would i check for the tags? if it's easier i can just send samples straight away

**Comment by OxygenCobalt** [comment] 2022-12-31 16:05
You can open it in a tag editor (kid3 will show them) and see if there are any tags with names like "MusicBrainz Album Artist ID" or "MusicBrainz Artist ID".

**Comment by KraXen72** [comment] 2023-01-01 10:31
![Screenshot_20230101-112651_DuckDuckGo.png](https://user-images.githubusercontent.com/21956756/210167621-9c001d43-1954-4b78-ac93-6ef542ff054c.png)
it does indeed appear i ran some of them through picard in the past. what would be a good option now? write a script to strip all MBID tags (saves time, but less accurate) or run everything through picard from now on? (more work now and in the future)

**Comment by OxygenCobalt** [comment] 2023-01-01 15:26
Auxio only leverages MBIDs in two cases:
- Splitting up artists or albums that have the same information so they aren't treated as the same entry
- Persisting music more reliably, which may help with making it less likely for songs to disappear from playlists when they are added.

Depends on how you feel about these benefits. I do think that Picard can automatically tag songs, saving the work of finding it's MBID.

Anyway, since this is intended behavior, I'll close this issue.

**Closed by OxygenCobalt** 2023-01-01 15:26 UTC
Labels: bug, music
