### ISSUE TITLE
Importing m3u files doesn't work on an SD card

### ISSUE THREAD

**Issue by Fuoxden** [OxygenCobalt/Auxio#871] opened 2024-09-16 08:43 UTC
### Describe the Bug/Crash

https://github.com/user-attachments/assets/cb85e024-f7aa-4906-b731-ce699a293726

### Describe the intended behavior

Playlist should import even if its on an SD card.

### What android version do you use?

Android 14

### What device model do you use?

Samsung A54 5G

### Provide a sample file

none

### Bug report

none

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-09-17 21:39
Duplicate of #700, Auxio only supports the "happy case" of M3U files stored on-device since it's nearly impossible to get a reasonable path otherwise. You need to wait until #322 for Auxio to traverse your SD card and find the M3U files (and their paths) directly.

**Closed by OxygenCobalt** 2024-09-17 21:39 UTC
Labels: bug

**Comment by Fuoxden** [comment] 2024-09-17 22:07
Okay, thank you for the response! I appreciate it :)

**Comment by OxygenCobalt** [comment] 2026-01-12 04:41
Hi again @Fuoxden, does this build let you export playlists?

Two caveats as it stands right now:
- M3U imports/exports are now forced-relative (ex. all outputs will assume the M3U sits at the root of the folder containing all of the music in the playlist) + can accidentally collide if you use several 3rd-party sources at once
  - I plan to fix the latter, this is just a prototype
- 3rd-party file manager paths can't be used to filter when in System mode (probably fine since System mode basically only works locally)

[Auxio_3rdParty.zip](https://github.com/user-attachments/files/24557284/Auxio_3rdParty.zip)
