### ISSUE TITLE
Feature request: delete file

### ISSUE THREAD

**Issue by halnine** [OxygenCobalt/Auxio#459] opened 2023-05-28 23:13 UTC
Enable user to delete files (especially currently playing file) from a context menu.

**Comment by OxygenCobalt** [comment] 2023-05-29 01:07
Duplicate of countless prior issues. Deletion cannot be added since it is obscenely difficult and device-specific with scoped storage restrictions.

**Closed by OxygenCobalt** 2023-05-29 01:07 UTC
