### ISSUE TITLE
Delete!

### ISSUE THREAD

**Issue by WeberAlex** [OxygenCobalt/Auxio#537] opened 2023-08-06 05:56 UTC
### Description

Nice and very polished Android music player, but where is the Delete menu?

### Problem solved

How do I manage my music collection on the go without a Delete option? I don't want to browser my audio files on my file manager to perform a delete action. I expect to do it while I am listening music, directly in the player.

### Other implementations

I have tried Simple Music Player, on F-Droid. I has a delete option.  I have tired Phonograph Plus, I am not positive, but I remember that it had a delete option.

### Benefit

Having the option to delete audio files on the go would benefit anyone frequently uploading and deleting their audio files.

I read the Why Are These Feature Missing/Song deletion page/chapter. If other players can do delete files, why Auxio can't? Browsing in a file manager, searching for a song, performing a delete action, that's such a chore.

I have to open 2 applications, remember the audio file name, search for it, etc. At least if I could copy the file name in the audio player, to past in Material Files, that would help, but there is no copy file name to my knowledge.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by e-zk** [comment] 2023-08-06 20:41
Duplicate of #350.

> Modern android has made this impossible due to the sheer amount of device-specific issues and insane limitations that have been introduced since Android 10. Poweramp uses SAF, yes, but I have no clue how it turns the file primitives into a music library given that it's proprietary.
> 
> Just use a file manager. If you want to delete an album, just organize your music into album folders.

**Comment by OxygenCobalt** [comment] 2023-08-07 19:09
See above. This is not planned for now.

**Closed by OxygenCobalt** 2023-08-07 19:09 UTC
Labels: enhancement

**Comment by WeberAlex** [comment] 2023-08-11 05:15
Fair enough (organizing my music into album folder). Thanks for the feedback.
