### ISSUE TITLE
Paused after completed

### ISSUE THREAD

**Issue by iBabu007** [OxygenCobalt/Auxio#665] opened 2024-01-10 07:44 UTC
How to stop music player?
If you want to listen only this music but after end it started another one then other until you stop the player manually.

Please if possible then add a button ("Paused after completed" add it inside three dot menu) Paused player when the music is completed.

**Comment by OxygenCobalt** [comment] 2024-01-10 13:56
Duplicate of #568.

**Closed by OxygenCobalt** 2024-01-10 13:56 UTC
