### ISSUE TITLE
The music is not found!

### ISSUE THREAD

**Issue by Admin31019** [OxygenCobalt/Auxio#636] opened 2023-12-08 22:23 UTC
### Describe the Bug/Crash

java.lang.NullPointerException
	at org.oxycblt.auxio.music.fs.BaseApi29MediaStoreExtractor$Query.populateFileInfo(SourceFile:53)
	at org.oxycblt.auxio.music.fs.BaseMediaStoreExtractor.consume(SourceFile:126)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreJob$1.invokeSuspend(SourceFile:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:19)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### Describe the intended behavior

Music is not found

### What android version do you use?

Android 14

### What device model do you use?

Huawei!  System is HarmyOS

### Bug report

java.lang.NullPointerException
	at org.oxycblt.auxio.music.fs.BaseApi29MediaStoreExtractor$Query.populateFileInfo(SourceFile:53)
	at org.oxycblt.auxio.music.fs.BaseMediaStoreExtractor.consume(SourceFile:126)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreJob$1.invokeSuspend(SourceFile:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:19)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-12-09 01:43
Duplicate of #592.

**Closed by OxygenCobalt** 2023-12-09 01:43 UTC
Labels: bug
