### ISSUE TITLE
Gapless playback

### ISSUE THREAD

**Issue by StarPepe** [OxygenCobalt/Auxio#110] opened 2022-03-25 21:48 UTC
Hello, would it be possible to add a gapless playback feature to Auxio, given that certain songs lead into one another? 

It interrupts the listening experience.

Thank you!

**Comment by OxygenCobalt** [comment] 2022-03-25 21:49
I've tried adding this back in #35, but technical limitations stopped me back then. I'll see if I can do this again.

**Comment by KraXen72** [comment] 2022-03-26 16:14
please do add this as an option though, not just gapless playback by default with no option to turn it off like deezer did a few years ago. i personally dislike gapless playback and would turn it off

**Comment by OxygenCobalt** [comment] 2022-03-26 16:16
I don't think I'll be able to do that. ExoPlayer automatically tries gapless playback if I configure it in the way required for this addition, so I don't think I'll be able to disable it.

**Comment by OxygenCobalt** [comment] 2022-04-28 22:01
Okay, quick update on this. For me to fit Gapless Playback into Auxio's architecture would require tighter coupling between the code that has the player and the code that exposes the playback state. I can do this, but I'm somewhat worried that it may introduce bugs due to the complicated process of initializing the playback system. I guess I can only wait and see when I make the next Auxio release.

**Comment by OxygenCobalt** [comment] 2022-05-24 18:55
Just to let you all know, once I implement #92, this should finally become technically possible.

**Comment by StarPepe** [comment] 2022-05-25 08:57
> Just to let you all know, once I implement #92, this should finally become technically possible.

Sounds great!

**Comment by animaldaydream** [comment] 2022-07-29 03:16
> I don't think I'll be able to do that. ExoPlayer automatically tries gapless playback if I configure it in the way required for this addition, so I don't think I'll be able to disable it.

If you *were* to implement gapful playback (um.) you would just place a period of silence between tracks.

By the way, there's not that many codecs that produce gaps between songs. Actually, the only one that comes to mind is MP3, and this usually gets fixed with software on any device with enough RAM, namely basically every modern Android phone.

It's just not the norm.

In fact, some music players go to the extreme and actually implement crossfade by default. Apple Music does this by default on any two tracks when not playing an album in order. (It actually works pretty well, surprisingly. But I still don't like it.)

**Comment by OxygenCobalt** [comment] 2022-07-29 03:31
> If you were to implement gapful playback (um.) you would just place a period of silence between tracks.

I can't append silence to the ExoPlayer audio stream. The only other option were to be switching between two completely different modes of operating the player queue, which I do not want.

> By the way, there's not that many codecs that produce gaps between songs. Actually, the only one that comes to mind is MP3, and this usually gets fixed with software on any device with enough RAM, namely basically every modern Android phone.

Really, Auxio's current playback issues are not caused by file format but rather that I load a single file into the player every time the song changes. The goal of this issue is for me to load the entire queue into the player, which would enable gapless playback.

> In fact, some music players go to the extreme and actually implement crossfade by default. Apple Music does this by default on any two tracks when not playing an album in order. (It actually works pretty well, surprisingly. But I still don't like it.)

I couldn't even implement crossfade if I wanted to. ExoPlayer devs don't like what it would do to the player timeline, as media items would not start and stop at clean points.

**Comment by OxygenCobalt** [comment] 2022-08-16 02:42
Turns out the method I wanted to leverage for this feature (Which was blocked by #92) won't work. I really do have to migrate the queue behavior to a system that ExoPlayer will tolerate. I'll push this back further.

**Comment by rahaaatul** [comment] 2022-10-02 05:56
@OxygenCobalt
> I couldn't even implement crossfade if I wanted to.

So there won't be crossfade in the app? I would love a crossfade option.

**Comment by OxygenCobalt** [comment] 2023-01-24 18:10
After 3.0.2 queue redesign, I think this is *almost* possible to be implemented. I fear certain edge cases regarding the way I want to approach this however.

**Comment by KraXen72** [comment] 2023-02-27 21:40
this would be really cool. if not possibe to be disabled/enabled dynamically, i wouldn't mind having to restart the app to toggle this. (i only want for some albums)

**Comment by KraXen72** [comment] 2023-02-27 21:47
or, you could have this always on and have a .15s or .25s long silence track that you internally insert between songs when they're about to end/start to simulate gaps.

the only reason for this would exist, is when somebody listens to shuffled songs a lot, it really does not make sense for a completely different song to play without a small gap.

**Comment by OxygenCobalt** [comment] 2023-02-27 21:57
I can't really do something like that. The issue is that with the current implementation in ExoPlayer, you would be able to "skip back" to the silence, which makes no sense.

**Comment by rhynec** [comment] 2023-02-28 00:13
Hmm, would the latter two solutions mentioned [here](https://github.com/google/ExoPlayer/issues/10967#issuecomment-1421258358)  make sense to add silence between tracks in Auxio? Option two would make the most sense to me, since it could make the silence belong to the end of any given track during playback, avoiding seeking within a single silence track and making skipping consistent.

**Comment by OxygenCobalt** [comment] 2023-02-28 00:14
Oh, I guess I could do that, but I'm not sure how I could make it settings-dependent.

**Comment by OxygenCobalt** [comment] 2023-03-06 16:21
Figured out that ExoPlayer's developers have already found ways to translate between the insane ExoPlayer queue and a saner linear queue in their media session implementation. Should allow me to depend my app on ExoPlayer's queueing system completely while still retaining the sensible playback behavior, at the cost of making literally every queue operation O(n) (Translation: Kinda slow).

**Comment by fishe-tm** [comment] 2023-06-30 18:31
vouching for this feature! auxio is amazing in every other aspect, but not having gapless playback ruins the sense of immersion in albums where each song feeds into the next

**Comment by midtsveen** [comment] 2023-08-25 23:51
I'm really excited about this feature too! Auxio is amazing in so many ways, but I gotta admit, not having gapless playback kinda ruins the experience for me, especially when I'm jamming to albums with seamless song transitions. Gapless playback is like fully enjoying the artist's flow and storytelling. I've got some albums that I just know would sound absolutely amazing with gapless playback.

**Comment by animaldaydream** [comment] 2023-08-26 00:05
When I need a gapless album, even if I picked it from Auxio, right now I just open it on AIMP. It's the only music player which has decent audio output functions for free and without ads, and the interface is decent. (It's based on building playlists from a file picker.)

It's not open source. But who would I complain to?

**Comment by OxygenCobalt** [comment] 2023-10-24 22:26
Before anyone plugs this, I am aware that Simple Music Player seemingly [got gapless playback working](https://github.com/SimpleMobileTools/Simple-Music-Player/blob/94d2ee9a4e76d5fd3251155a08aeca7871a9c139/app/src/main/kotlin/com/simplemobiletools/musicplayer/playback/player/SimpleMusicPlayer.kt) with ExoPlayer.

I don't think this will help me much. It seems more or less like a hacky workaround that probably has some really bad performance characteristics and subtle bugs to it.

**Comment by OxygenCobalt** [comment] 2023-10-24 22:30
I'm also very sorry about the delay here. This is one of my priority features, but I have far too many classes this semester and can't do much on Auxio except for a few hours every month and a half or so.

**Comment by OxygenCobalt** [comment] 2024-01-07 22:57
I've successfully hacked together an initial gapless playback implementation. It should be usable enough to play with, but has enough quirks to probably not be a daily driver. Notably:

- Queue editing is really delayed right now, mostly because I'm jumping the gun on notifying the app that the queue has changed before it actually has internally. I'm still figuring out how to fix this.
- Any kind of playback-related setting is broken right now, as I had to rip out all the code related to that.
- Repeat mode is busted, again because I've ripped out the code related to that.
- The code is extremely inefficient. The debug build is already going to be slow, but all the times I'm unscrambling the queue really slows the app down. I'm still working on this.

[Auxio_Gapless1.zip](https://github.com/OxygenCobalt/Auxio/files/13855176/Auxio_Gapless1.zip)

Better builds soon (tm)

**Comment by OxygenCobalt** [comment] 2024-01-09 02:15
Alright, I'm blocked by https://github.com/androidx/media/issues/954 for now sadly. ExoPlayer seemingly currently has completely broken item moving behavior, so queue edits will be broken until a fix can be patched in.

**Comment by KraXen72** [comment] 2024-01-09 07:09
me when i'm in a 'being unreasonable and hard to work with' competition and my opponent is media3

**Comment by OxygenCobalt** [comment] 2024-01-09 18:33
> me when i'm in a 'being unreasonable and hard to work with' competition and my opponent is media3

Ugh, my mood exactly. You know that the same code used to insert new media items (i.e play next) and the code used to reshuffle media items calls the *same function?* I literally have to dynamically swap out the shuffle order in transit to avoid that.

**Comment by OxygenCobalt** [comment] 2024-01-09 20:55
Alright, I'm actually just stupid and didn't realize that moving items in ExoPlayer does not swap them as I normally designed moving items to do in the app.

Here's a new APK. Should be significantly less gotcha-filled, but half of the playback features are still broken lol
[Auxio_Gapless2.zip](https://github.com/OxygenCobalt/Auxio/files/13878945/Auxio_Gapless2.zip)

**Comment by OxygenCobalt** [comment] 2024-01-09 20:58
[Auxio_Gapless2.zip](https://github.com/OxygenCobalt/Auxio/files/13878985/Auxio_Gapless2.zip)

**Comment by KraXen72** [comment] 2024-01-09 23:04
incredible progress over such a short amount of time <33

**Comment by OxygenCobalt** [comment] 2024-01-12 15:34
I think my last blocker here is reimplementing playback state saving (this should be really easy, I already worked it out prior), and then it should be good to go for a major release. Don't know when I will have the ability to do it though since school is starting again.

**Comment by OxygenCobalt** [comment] 2024-01-14 03:48
Complete Gapless Debug Build: [Auxio_Gapless3.zip](https://github.com/OxygenCobalt/Auxio/files/13930240/Auxio_Gapless3.zip)

Now you just have to look out for various regressions. There should be no major behavioral changes.

**Comment by OxygenCobalt** [comment] 2024-01-14 04:00
I'll also warn that I've heard from various places on the ExoPlayer repository that OGG files don't have good gapless playback support. Don't know if that's changed or not.

**Closed** 2024-01-15 23:03 UTC
Labels: enhancement, doesnt-follow-template, playback, complex
