### ISSUE TITLE
Seekbar

### ISSUE THREAD

**Issue by saltsoftdrink** [OxygenCobalt/Auxio#716] opened 2024-02-20 08:44 UTC
### Description

Add Squiggly Progress bar

### Other implementations

I didn't get this question 

### Benefit

It looks cool and fresh

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by chocmake** [comment] 2024-02-20 12:23
Dupe of #130

**Closed as completed** 2024-02-20 13:43 UTC
Labels: enhancement
