### ISSUE TITLE
Swipe down to refresh music

### ISSUE THREAD

**Issue by Shivamhobbyist** [OxygenCobalt/Auxio#653] opened 2023-12-26 12:05 UTC
### Description

Like this on home screen

https://github.com/OxygenCobalt/Auxio/assets/78287172/12c7b7d5-1d57-4d08-9244-13f46e3a0bb1

### Problem solved

No problem just a suggestion

### Other implementations

Nothing

### Benefit

It will simple and easy 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-12-27 02:08
Duplicate of #127 and probably a few others. This is a pattern best suited for individual screens with individual lists of content. Auxio's music library is so intertwined that swiping up to refresh functionally requires everything to be reloaded, not just what's currently on the screen. Additionally, the more UI things I add, the more unstable and janky the UI becomes, so I generally avoid adding things like this.

**Closed by OxygenCobalt** 2023-12-27 02:08 UTC
Labels: enhancement
