### ISSUE TITLE
Add support for webp in covers lookup (the app already supports decoding them)

### ISSUE THREAD

**Issue by ynhame** [OxygenCobalt/Auxio#852] opened 2024-08-20 06:01 UTC
### Description

I just tried to use a webp cover named "cover.webp" and it was not recognized.

As a work around renaming it from "cover.webp" to "cover.png" resolved the issue.

so to app does support decoding webp images, but filters them out while searching for possible covers in the album folder.

would be nice if this work around was not necessary.

### Problem solved

The app can already decode webp images, but it filters them out while looking for images in the folder.

### Other implementations

I tried some other players to answer this question:

musicolet: no support at all
blackplayer: suppots just fine
MPV: suppots just fine

if you want me to test in more players, just tell me

### Benefit

smaller file sizes (and possibly faster loud times?) without loss of quality

in my tests I could reduce the size of the images by 50% going from jpg to webp 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-08-21 00:54
Duplicate of #104. Android has a janky half-supported version of this after Android 11 that I implicitly rely on, I have to make my own implementation.

**Closed by OxygenCobalt** 2024-08-21 00:54 UTC
Labels: enhancement
