### ISSUE TITLE
app won't start after first launch

### ISSUE THREAD

**Issue by kuesji** [OxygenCobalt/Auxio#90] opened 2022-03-01 14:57 UTC
#### Describe the bug/crash:

app won't start after first launch if theme changed to dark from automatic.

#### Steps To Reproduce the bug/crash:

1. open the app
2. set theme to dark from automatic at app's settings ( not system settings )
3. restart the app ( remove from recents and start from launcher )

#### Logs/Stack Traces:

```
03-01 17:45:14.919  8723  8723 E AndroidRuntime: FATAL EXCEPTION: main
03-01 17:45:14.919  8723  8723 E AndroidRuntime: Process: org.oxycblt.auxio, PID: 8723
03-01 17:45:14.919  8723  8723 E AndroidRuntime: java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:2)
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at org.oxycblt.auxio.ui.MemberBinder.getValue(MemberBinder.kt:3)
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at org.oxycblt.auxio.playback.PlaybackFragment.getBinding(PlaybackFragment.kt:1)
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at org.oxycblt.auxio.playback.PlaybackFragment$$ExternalSyntheticLambda10.run(R8$$SyntheticClass:2)
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6702)
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-01 17:45:14.919  8723  8723 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
03-01 17:45:14.930  8723  8744 E ion     : ioctl c0044901 failed with code -1: Invalid argument
```

#### Screenshots:

standart "app is stopped. show info or close app" dialog shown only

#### Phone Information:

Nokia 3, Android 9, Stock Rom

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2022-03-01 14:59
Duplicate of #80. A fix should arrive in the next version.

**Closed by OxygenCobalt** 2022-03-01 14:59 UTC
Labels: bug

**Comment by kuesji** [comment] 2022-03-01 15:21
oh. i didn't check closed issues for duplicates, my bad.
maybe keeping #80 open until it fixed is better because you know closed issue means fixed one.

**Comment by OxygenCobalt** [comment] 2022-03-01 15:57
I already do that, it's just (personally) it's clearer for me to close issues that have already been fixed on my end. I'll pin the other issue for now.

Given that this issue is somewhat widespread, I'll try to create a 2.2.2 release soon so that this can be fixed right away.
