### ISSUE TITLE
a way to edit the meta data of the song

### ISSUE THREAD

**Issue by talal12bfk** [OxygenCobalt/Auxio#82] opened 2022-02-21 20:12 UTC
#### Describe the feature you want to implement:
in the three dot menu of every track an option to edit the name of the artist, the genre, the title and the album, would be nice :-)
#### Is your feature request related to a problem? Please describe:
not realy but most songs that u download comes without metadata so the are pretty mixed up

#### Do other music players handle this? If so, how?
yes they but im not realy a good dev so i dont know how

#### Why do you think this will improve everyone's usage of Auxio?
im a little bit of an perfectionist so it would not be bad to have an option to edit the meta data so the would be sorted right

#### Due Diligence:
- [ √] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ √] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [√ ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment] 2022-02-21 20:39
Duplicate of #33. Use an external tag editor.

**Closed by OxygenCobalt** 2022-02-21 20:39 UTC
Labels: enhancement
