### ISSUE TITLE
[Feature] Sort by "random" option

### ISSUE THREAD

**Issue by Kisuke-CZE** [OxygenCobalt/Auxio#840] opened 2024-07-24 14:31 UTC
### Description

Hi,

I would love if this app allow me to sort albums/artists as random. Anytime I switch to tab which is selected to be sorted as "random", order should be randomized again.

I already [suggested this feature to Mucke app](https://github.com/moritz-weber/mucke/issues/179) in different way. But as Auxio app (and Vanilla Music also) has more straightforward interface, i believe that having option "Sort by: random" is more suitable for this app.

### Other implementations

For example Kodi implements this as smart-playlist option to select defined number of random albums. In default Estuary skin it is available right in Music subsection:
![Screenshot from kodi](https://kodi.wiki/images/4/4c/Estuary_home_music_library.png)

### Benefit

Random sorting allows user to quickly pick some random music (album or artist mainly) from library. If someone has large library and wants to quickly pick something random (to not listen always the same), this can be easy way.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-07-25 03:14
Judging by your reference to Kodi, his is in intent a duplicate of #260/"for you" page. There's not a good place to put a random selection of music items, tacking it on a sort mode breaks every UI invariant I've built, and in general I don't like "faking" recommendations to mimick spotify & friends. Sorry.

**Closed by OxygenCobalt** 2024-07-25 03:14 UTC
Labels: enhancement
