### ISSUE TITLE
Ability to remove songs from a playlist only

### ISSUE THREAD

**Issue by sao-g** [OxygenCobalt/Auxio#862] opened 2024-08-29 22:52 UTC
### Description

Please add the ability to remove songs from a playlist (and not from phone).

### Problem solved

Sometimes i mistakenly add a song twice, or include songs from the wrong album to the wrong playlist. To fix that, i have no option other than to delete the playlist completely and start again. Adding this delete song from a playlist feature will help solve this issue.

### Other implementations

In other players, when you go to the playlist, you just tap and hold the song and from the options, you can select 'remove from playlist.'

### Benefit

This feature will allow anyone to remove a song from their playlist. If they have made a mistake in their playlist by adding the wrong song, or adding the same song twice, or maybe doesn't like an existing song anymore within a playlist, then they can safely delete it, without deleting the entire list.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-08-29 23:02
Duplicate of #624, you can delete now, you just need to first edit the playlist by clicking on the pencil and then swipe away songs.

**Closed by OxygenCobalt** 2024-08-29 23:02 UTC
Labels: enhancement
