### ISSUE TITLE
[UX] Scroll bar for playlists, albums, artists, genres

### ISSUE THREAD

**Issue by OIRNOIR** [OxygenCobalt/Auxio#832] opened 2024-07-18 06:53 UTC
### Description

I would like a scroll bar to be added to the interla view of playlists, albums, and artists (and similar song-list views), similar to the scroll bar currently implemented on the five main tabs "Playlists, songs, albums, genres, artists". Obviously, these scroll bars wouldn't indicate alphabetical letters because most playlists and albums aren't alphabetical.

### Problem solved

My problem is that I have several extremely long playlists (on the order of 1,000-1,500 songs) and, when I add a song to the playlist that has already been added, I find that I have to scroll ALLLLLLLL the way to the bottom manually. This would be much MUCH simpler aided by a scroll bar, and make navigating large playlists just as much of a breeze as navigating the rest of the library itself.
It would also be useful for navigating individual artists via the artists page who create large quantities of content.

### Other implementations

I don't know about any other music players and whether they have this implemented. I just know of Auxio's great implementation of a scroll bar for the five main tabs of the app.

### Benefit

Navigating large playlists and albums, viewing artists with lots of content, and opening the mysterious "Unknown genre" folder would all be much much easier.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-07-19 02:19
Duplicate of #229, luckily I've started to build the UI I need for this (requires some more polish) and it should get added soon.

**Closed by OxygenCobalt** 2024-07-19 02:19 UTC
Labels: enhancement

**Comment by OIRNOIR** [comment] 2024-07-19 03:05
Thank you! I didn't think that issue was related because it said something about a "details" view(?)
Sorry for the duplicate!
