### ISSUE TITLE
Searching/displaying "lyrics" exif tags

### ISSUE THREAD

**Issue by SergioK29** [OxygenCobalt/Auxio#907] opened 2024-11-07 01:48 UTC
### Description

Songs from deezer/spotify etc can have "Lyrics" exif tag, would be cool if we can search within lyrics and/or open a lyrics screen if they are available

```
Vorbis:Publisher "Parlophone UK"
Vorbis:ISRCNumber "GBAYE0800265"
Vorbis:Lyrics "I used to rule the world\r\nSeas would rise when I gave the word\r\nNow in the morning, I sleep alone\r\nSweep the streets I used to own\r\n\r\nI used to roll the dice...
```

### Problem solved

If you wanna read lyrics and your audio files have embedded lyrics, or you remember lyrics of a song but don't remember the title/artist and wanna search by lyrics

### Other implementations

Spotify lets you search by lyrics, and lets you display lyrics if they are known

### Benefit

Lyrics reading, very nice sir
Lyrics searching, very nice sir

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-11-07 18:15
Duplicate of #48, I generally don't view lyrics as a good in-scope feature for the app. Sorry.

**Closed by OxygenCobalt** 2024-11-07 18:15 UTC
Labels: enhancement
