### ISSUE TITLE
Support Embedded lyrics

### ISSUE THREAD

**Issue by xmha97** [OxygenCobalt/Auxio#123] opened 2022-04-21 18:45 UTC
Please support embedded lyrics

**Comment by OxygenCobalt** [comment] 2022-04-21 19:16
Duplicate of #19, #48, and #86. I don't [see any personal benefit](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) in lyrics as most my music is instrumental.

**Closed by OxygenCobalt** 2022-04-21 19:16 UTC
Labels: enhancement
