### ISSUE TITLE
crashing on startup

### ISSUE THREAD

**Issue by Simplenuity** [OxygenCobalt/Auxio#98] opened 2022-03-08 11:06 UTC
#### Describe the bug/crash:

When trying to start Auxio (version 2.2.1) it either crashes without error message or any other info/screen. Or (usually) starting with the second attempt it shows audio file listing for a split second, then crashes and shows error message (see below).
No problems with older versions.

#### Expected behavior

Open Auxio and use it.

#### Steps To Reproduce the bug/crash:
1. Go to app menu
2. Click on Auxio
3. Crash as described above
Error message:

> java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:2)
	at org.oxycblt.auxio.ui.MemberBinder.getValue(MemberBinder.kt:3)
	at org.oxycblt.auxio.playback.PlaybackFragment.getBinding(PlaybackFragment.kt:1)
	at org.oxycblt.auxio.playback.PlaybackFragment$$ExternalSyntheticLambda10.run(R8$$SyntheticClass:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

#### Logs/Stack Traces:
access denied
If error message above is not enough, please let me know.

#### Phone Information:
Xiaomi Mi Max 3
MIUI Global 12.0.1 stable
Android 10

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2022-03-08 13:24
Duplicate of #80. This will be fixed in 2.2.2.

**Closed by OxygenCobalt** 2022-03-08 13:24 UTC
Labels: bug

**Comment by Simplenuity** [comment] 2022-03-08 13:39
Thanks!
