### ISSUE TITLE
Overscroll to refresh library

### ISSUE THREAD

**Issue by dddnk** [OxygenCobalt/Auxio#805] opened 2024-06-20 07:54 UTC
### Description

My idea is that you can overscroll at the top of the list to refresh the music, similar to what is seen in other applications and browsers.
This feature could be a toggle in settings if people think they will accidentally trigger this.

### Problem solved

I sometimes fell that diving into settings to refresh music is slow, and is frustrating if it is done repeatedly. (if I am downloading music, and am unsure if it is finished, for example)

### Other implementations

The music player I used previously, Samsung music, simply checked the filesystem once every few seconds. Auxio already has a feature for that, and Samsung music's feature drained the battery a bit.

### Benefit

This feature makes refreshing the library much simpler, in a straightforward way.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-06-21 02:30
This is a duplicate of prior issues and is mostly technically undesirable. The main UI is extremely bloated and fragile, so adding another behavior (like swipe to refresh) is guaranteed to make it less stable and usable. Additionally, the tiny loading indicator that swipe to refresh has is not really compatible with Auxio's current UI (especially with long-term loader tasks).

**Closed by OxygenCobalt** 2024-06-21 02:30 UTC
Labels: enhancement
