### ISSUE TITLE
Love and Lyrics

### ISSUE THREAD

**Issue by noa7777** [OxygenCobalt/Auxio#772] opened 2024-05-06 13:29 UTC
### Description

No feature to mark favorite songs

There is no function to display lyrics

### Other implementations

The desktop widget function of this software is too simple. Can you add a star button to save your favorite song

### Benefit

...

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-05-06 17:57
Favorites is a duplicate of #448.

Lyrics have been rejected multiple times before, the technical difficulty in implementing them and displaying them is too large, especially when some users (like myself) listen to mostly instrumental music and need them.

**Closed by OxygenCobalt** 2024-05-06 17:57 UTC
Labels: enhancement
