### ISSUE TITLE
Add a close X button before the Play button to close the song.

### ISSUE THREAD

**Issue by shalomcohen10** [OxygenCobalt/Auxio#867] opened 2024-09-11 12:21 UTC
### Description

When song plays, and it showed at the bottom layout, make an option to close it totally with X button. This is a necessary and very basic feature for a music app. Can't understand why didn't you think of it :D other than that, GREAT music player!

### Other implementations

Other music apps have it!

### Benefit

Better experience!

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-09-11 23:43
Duplicate of #478.

**Closed by OxygenCobalt** 2024-09-11 23:43 UTC
Labels: enhancement
