### ISSUE TITLE
Unable to read artist name

### ISSUE THREAD

**Issue by NGeek752** [OxygenCobalt/Auxio#50] opened 2021-09-27 14:24 UTC
As described in the title, somehow Auxio couldn't read the artist of the songs on my phones.

#### Phone Information:
Android 9 and 7

#### Due Diligence:

- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2021-09-27 15:21
I'll need more information.
- Do you have a logcat/stack trace?
- What phone model/ROM are you using?
- Can I have a possible sample file so I can investigate it's metadata?
- What artist names are you getting? "Unknown Artist", "<unknown>", "null", or just blank?

If you provide me with some extra context I'll be able to discern the problem, it might already be fixed in the development version.

**Comment by OxygenCobalt** [comment] 2021-10-17 19:57
> I assume the name below the song title is the artist name

Oh, its actually `Artist Name / Album Name`. So if I'm getting this correctly, you're getting `[Last Imported Song Name] / Music`

I've really not encountered another instance of `MediaStore` like this before. What other android music players are you not getting the issue? I know that VLC and Vanilla music parse audio tags themselves, and so if those work but other players like Phonograph don't then it's yet another instance of an OEM crippling the Media APIs for no reason.

> 3. Sorry I don't know how to do that

You could just upload one of your music files that has the issue.

**Comment by NGeek752** [comment] 2021-11-22 09:58
Sorry for the delay (not here very often)
> So if I'm getting this correctly, you're getting [Last Imported Song Name] / Music on every song

That's right.

> What other android music players are you not getting the issue? 

Music Player Go doesn't have this issue for me. I'm not sure about others

I got one over here. NCS should be safe:
https://drive.google.com/file/d/1Mh5lWqLgXb4uKY0z69puZRxrL_9zCr6n/view?usp=sharing

Thanks!

**Comment by OxygenCobalt** [comment] 2021-11-23 18:46
Looks like my device reads it just fine. This seems like a `MediaStore` issue that MPGO somehow mitigated. I'll try to check it out.

**Comment by OxygenCobalt** [comment] 2021-11-25 18:09
I just considered that it might be the way that I was indexing artists in 1.4.2.

1.4.2 reads artist names from the album database. MPGO reads artist names from the song database. Your device's `MediaStore` implementation may have borked getting the artist name from the albums database but not the songs database. This means that the upcoming 2.0.0 release may fix this issue as I now index artists from the song database.

**Comment by NGeek752** [comment] 2022-01-20 04:52
I tested the latest version 2.0.1 but it's the same
A sreenshot for reference:
https://drive.google.com/file/d/1uPOW0JJ6rXdiwxhuASu2BmLpqpw_KddY/view?usp=sharing

Maybe my Android version is a bit old(?) (I used my Android 9 phone for testing)
Thanks for your hard work!

**Comment by OxygenCobalt** [comment] 2022-01-22 03:56
This truly is the most inexplicable issue I've ever seen. MPGO does more or less the exact same thing that my app does, yet it does not have this issue. Can you provide an example of what Music Player GO shows for the artist name? I can possibly trace the issue back to something more specific.

As for your theory about the old android version, the APIs for indexing music have more or less remained unchanged since 2011 (to the detriment of every music player), so version doesn't really matter here. It's more-so OEMs crippling the music APIs either due to stupidity or to railroad users into their music app that relies on private extensions to the OS instead.

**Comment by NGeek752** [comment] 2022-01-23 08:51
Yeah sure! 
Music Player Go:
https://drive.google.com/file/d/170tP0C1XrYg3P-j7QbTCLMhwvkfzdn09/view?usp=drivesdk

I see. Then it's a really wierd issue... and seems like only I encounter this so far

Btw, my phone is HTC Desire 19+, not one that has many users I guess. Not sure if it helps

**Comment by OxygenCobalt** [comment] 2022-02-06 00:10
I think I've found a possible discrepancy between MPGO's implementation and mine. In technical terms, they used the applications content resolver while I used the content resolver of a local context. Other than that, the only differences I found were in their wording of `MediaStore` columns and their order, which I doubt changed much.

Perhaps try this APK? 
[Auxio_AppContext.zip](https://github.com/OxygenCobalt/Auxio/files/8009151/Auxio_AppContext.zip)

**Comment by NGeek752** [comment] 2022-03-08 13:41
Hi there!

I don't know how to install from the zip file (after some research).
However,
I just installed from your latest version, and this issue is solved!!! (check out the image below)
https://drive.google.com/file/d/1--4ptJMihBSOzW_aX-IRvNWGHpnNVsvd/view
Could be the discrepancy you mentioned above

Can't thank you enough for this! Sorry for my delayed response
Wish you the best!

**Comment by OxygenCobalt** [comment] 2022-03-08 13:58
That's great! And yes, this does mean that the issue I mentioned above was the cause of this issue. Thanks for holding out for so long.

**Closed by OxygenCobalt** 2022-03-08 13:58 UTC
Labels: bug, music
