### ISSUE TITLE
Adding an option to favorite songs inside a playlist

### ISSUE THREAD

**Issue by Fuoxden** [OxygenCobalt/Auxio#878] opened 2024-10-03 04:36 UTC
### Description

i have over 1,000 songs, one of my playlists has 500 songs, if i would want to find my favorites i would have to scroll for a really REALLY long time, lets say you have a song at the bottom of the 500 song playlist, it would take you a while to scroll down, Especially if you dont know the exact name of the song.

### Problem solved

Spotify has something called 'liked songs' its basically a playlist that is made when you like a song, so what if their was a default playlist that was named favorites? So you could like a song, and it would place the song in the playlist! The playlist would work like a normal one, the only thing you wouldnt be able to do is delete it, the only way to get rid of it would be to go to the preferences and turn it off, it would also be at the very top of the playlists so you wouldnt have to find it! i think that would be pretty neet!

### Other implementations

So, why not have a possibly have a 'favorites' tab in the 'library tabs'? kinda like this mockup i did: 
![Screenshot from 2024-10-02 23-26-04](https://github.com/user-attachments/assets/6d161b38-19c8-4a7f-9a3c-043ec58cf42f)

when you open the tab it could have a list of all the favorites, or it could make almost a copy of the playlist name but only add the songs you favorited to it, if that makes sense 

### Benefit

Having all your favorites in one playlist, all you need to do is find them once, then add them to your favorites, and then your done!

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-10-11 17:10
Duplicate of #448.

**Closed by OxygenCobalt** 2024-10-11 17:10 UTC
Labels: enhancement
