### ISSUE TITLE
Albums are created based on Artist when Album Artist tag is empty

### ISSUE THREAD

**Issue by skj-skj** [OxygenCobalt/Auxio#737] opened 2024-03-08 06:38 UTC
### Describe the Bug/Crash

I have a music album in my device and Album Artist tag is empty for those songs/audio files

when Album Artist Tag is empty, app will split the album based on Artist of the individual songs.

when I updated the Album Artist tag for each song lets day `Foo`, then app correctly shows one album.

### Describe the intended behavior

App should show only one album and not split based on individual artist of the song.

### What android version do you use?

Android 13

### What device model do you use?

Oppo A77s

### Provide a sample file

[FooBarAlbum.zip](https://github.com/OxygenCobalt/Auxio/files/14534207/FooBarAlbum.zip)

### Bug report

NA

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by skj-skj** [comment] 2024-03-08 06:39
Screen Shot:
![Screenshot_2024-03-08-12-04-26-85_e7dcd68fdcfdc2ab307738dbc82b3952](https://github.com/OxygenCobalt/Auxio/assets/53490263/9483df8a-e909-4f61-8284-9f7bec038ddc)

**Comment by OxygenCobalt** [comment] 2024-03-08 18:42
This is intended behavior. Auxio cannot combine albums by multiple artists into one, as that would mean that albums by different artists with the same name would be merged. This is what the "Album artist" tag is explicitly designed to fix, and I would recommend retagging your library.

**Closed by OxygenCobalt** 2024-03-08 18:42 UTC
Labels: bug
