### ISSUE TITLE
Albums grid view 

### ISSUE THREAD

**Issue by Athzzzx** [OxygenCobalt/Auxio#689] opened 2024-01-22 08:02 UTC
The default view is in list mode, which makes the album thumbnails very small to see in a big library.

Grid mode that shows two to three album artworks per row will make browsing more comfortable.

**Comment by e-zk** [comment] 2024-01-22 08:05
I wouldn't mind a grid view. 

However this issue has been discussed before. It's not going to be added. 

Duplicate of #611 and #672

**Closed** 2024-01-22 12:55 UTC
