### ISSUE TITLE
Tag Editor

### ISSUE THREAD

**Issue by Github-contribute** [OxygenCobalt/Auxio#138] opened 2022-05-27 02:59 UTC
#### Describe the feature you want to implement:

Audio Tag Editor

#### Why do you think this will improve everyone's usage of Auxio?

I have separate app for this, only for tag editor. If u implement this, it great for use one and only app. I really miss this in auxio. 
1. Change cover picture
2. Change artist picture
3. Edit metadata

#### Due Diligence:
- [ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ ] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [ ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment] 2022-05-27 03:08
Duplicate of #82 and #33. Auxio is a music player. It does not edit tags and it never will.

**Closed by OxygenCobalt** 2022-05-27 03:08 UTC
Labels: enhancement

**Comment by ian1ilych** [comment] 2022-09-27 15:17
Did you know that Oto Music actually added that feature?

**Comment by OxygenCobalt** [comment] 2022-09-27 19:37
Yes. And I am not trying to be like Oto Music.
