### ISSUE TITLE
volume knob

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#522] opened 2023-07-19 21:34 UTC
### Description

might be better as a separate app but a software volume knob for all system apps, why? even on max volume some songs and files are too quirt so adding gain to it before it goes to the speakers would be great

### Other implementations

they have knobs or sliders

### Benefit

loudness

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by illdeletethis** [comment] 2023-07-19 21:43
![Screenshot_20230719-234234_Auxio](https://github.com/OxygenCobalt/Auxio/assets/62331598/1ebdd6b7-71d4-4ee8-a720-2e76a96139d6)
Settings > Audio

**Comment by RustoMCSpit** [comment] 2023-07-19 22:27
> ![Screenshot_20230719-234234_Auxio](https://user-images.githubusercontent.com/62331598/254717907-1ebdd6b7-71d4-4ee8-a720-2e76a96139d6.png) Settings > Audio

oh cool!!!

**Comment by OxygenCobalt** [comment] 2023-07-20 02:14
This is already a duplicate of prior issues anyway. The system audio slider exists.

**Closed by OxygenCobalt** 2023-07-20 02:14 UTC
Labels: enhancement
