### ISSUE TITLE
music not loading 

### ISSUE THREAD

**Issue by dirrology** [OxygenCobalt/Auxio#692] opened 2024-01-24 14:45 UTC
### Describe the Bug/Crash

1. Open app
2. Shows music loading failed

### Describe the intended behavior

It should load the music

### What android version do you use?

Android 13

### What device model do you use?

Samung galaxy a52 5g

### Bug report

android.database.sqlite.SQLiteException: near "OR": syntax error (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _id, date_added, date_modified, _size, duration, mime_type, title, year, album, album_id, artist, album_artist, _display_name, volume_name, relative_path, cd_track_number, disc_number FROM audio WHERE ((((is_pending=0 AND NOT _modifier=4) OR (is_pending=1 AND lower(_data) NOT REGEXP '.*/\.pending-(\d+)-([^/]+)$' AND owner_package_name IN ( 'org.oxycblt.auxio' )))) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND (NOT _size=0 AND is_music=1 AND  ( OR (volume_name LIKE ? AND relative_path LIKE ?)))
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1226)
	at android.content.ContentResolver.query(ContentResolver.java:1158)
	at android.content.ContentResolver.query(ContentResolver.java:1114)
	at org.oxycblt.auxio.music.fs.StorageUtilKt.safeQuery(Unknown Source:6)
	at org.oxycblt.auxio.music.fs.MediaStoreExtractorImpl.query(SourceFile:377)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreQueryJob$1.invokeSuspend(SourceFile:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.fragment.app.Fragment$4.run(SourceFile:43)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-01-24 15:35
Duplicate of #667.

**Closed by OxygenCobalt** 2024-01-24 15:35 UTC
Labels: bug
