### ISSUE TITLE
A Better Artists Credit

### ISSUE THREAD

**Issue by polyester2023** [OxygenCobalt/Auxio#649] opened 2023-12-21 03:49 UTC
### Description

Currently, Auxio force every artists to have a standardize name. The problem with this approach is that sometimes one artists could have multiple names in different language, styles, or sometimes even typo and that typo sometimes is intentional. Also an artists could colaborate with different artists.

### 1. [TRACK ARTISTS CREDIT]
![1](https://github.com/OxygenCobalt/Auxio/assets/154487331/dcda13bd-9b9b-4d5b-89c8-6291ed882a70)
Based on the image above, the artists credit of a track is "**Hiroshi Okubo (nanosounds.jp) feat. SAK., TA-KO**". Auxio currently split the artist with comma without any joint phrases, so there should be two artists because there are only one comma. But wait a minute, aren't there a joint phrases that would make it a 3 artists credit. Also the artists credit above is wrong because the actual artists credit is "**Hiroshi Okubo feat. TA-KO**".

This is the tag for this song.
MUSICBRAINZ_ARTISTID=41d3a5ee-f479-44fb-959b-e517ef2aa00e
MUSICBRAINZ_ARTISTID=97bbc527-8064-4bb4-9a38-2309285318c9
ARTIST=Hiroshi Okubo feat. TA-KO
ARTISTSORT=Okubo, Hiroshi feat. TA-KO
ARTISTS=Hiroshi Okubo
ARTISTS=TA-KO

This is the tag for another song.
MUSICBRAINZ_ARTISTID=41d3a5ee-f479-44fb-959b-e517ef2aa00e
MUSICBRAINZ_ARTISTID=8bd57bc9-666f-4da7-a7ad-1b6e7aeec8bd
ARTIST=Hiroshi Okubo (nanosounds.jp) feat. SAK.
ARTISTSORT=Okubo, Hiroshi (nanosounds.jp) feat. SAK.
ARTISTS=Hiroshi Okubo
ARTISTS=SAK.

As you can see, the both artists id is the same "MUSICBRAINZ_ARTISTID=41d3a5ee-f479-44fb-959b-e517ef2aa00e" for the artist "Hiroshi Okubo" but both song thankfully have the same "ARTISTS=Hiroshi Okubo". The bold part of this "ARTIST=Hiroshi Okubo **(nanosounds.jp) feat.** SAK." (including space) is actually the joint phrases.

![2](https://github.com/OxygenCobalt/Auxio/assets/154487331/e8c47cb3-2916-4053-87c6-e300a5f0776a)
Ideally. Auxio should just make the track artists credit to "ARTIST=**Hiroshi Okubo feat. TA-KO**", and when we press go to artists, it should show "ARTISTS=**Hiroshi Okubo**" and  "ARTISTS=**TA-KO**"

### 2. [ALBUM ARTISTS CREDIT]
This is the issue from  #648
For some reason, auxio uses the same album artists, even though the album is different.

MUSICBRAINZ_ALBUMARTISTID=5005beb6-9da2-48ba-bfd9-aa8ddc6d0117
MUSICBRAINZ_ALBUMARTISTID=ce4e45e8-233c-45d3-ac69-8a9ea57f42b6
MUSICBRAINZ_ALBUMARTISTID=38707e15-2bef-43bc-82d0-2a7e82acb199
MUSICBRAINZ_ALBUMARTISTID=0aa7ae8a-a5ff-46a1-8729-ffa4392cd2d6
MUSICBRAINZ_ALBUMARTISTID=f6f03430-b376-4e94-b79e-a7956f976a2f
ALBUMARTIST=MAISONdes feat. 堂村璃羽 & 301 & GeG & 安本彩花
ALBUMARTISTSORT=MAISONdes feat. Domura, Riu & 301 & GeG & Yasumoto, Ayaka

MUSICBRAINZ_ARTISTID=5005beb6-9da2-48ba-bfd9-aa8ddc6d0117
MUSICBRAINZ_ARTISTID=ce4e45e8-233c-45d3-ac69-8a9ea57f42b6
MUSICBRAINZ_ARTISTID=38707e15-2bef-43bc-82d0-2a7e82acb199
MUSICBRAINZ_ARTISTID=0aa7ae8a-a5ff-46a1-8729-ffa4392cd2d6
MUSICBRAINZ_ARTISTID=f6f03430-b376-4e94-b79e-a7956f976a2f
ARTIST=MAISONdes feat. 堂村璃羽 & 301 & GeG & 安本彩花
ARTISTSORT=MAISONdes feat. Domura, Riu & 301 & GeG & Yasumoto, Ayaka
ARTISTS=MAISONdes
ARTISTS=堂村璃羽
ARTISTS=301
ARTISTS=GeG
ARTISTS=安本彩花

The album artists for this album is "**MAISONdes feat. 堂村璃羽 & 301 & GeG & 安本彩花**" which is the same for the track artists because it's a single. What I think is happening is that there are 5 "MUSICBRAINZ_ALBUMARTISTID" and only 1 "ALBUMARTIST"

I think Auxio should ignore music "MUSICBRAINZ_ALBUMARTISTID" if there are multiple of them

### Other implementations

Other music player just ignore the musicbrainz id an just use based on the names, but this will create multiple duplicate artists

### Benefit

This would benefit everybody

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-12-21 03:51
Duplicate of #582. I'm already considering this.

**Closed by OxygenCobalt** 2023-12-21 03:51 UTC
Labels: enhancement

**Comment by OxygenCobalt** [comment] 2023-12-21 04:02
> The album artists for this album is "MAISONdes feat. 堂村璃羽 & 301 & GeG & 安本彩花" which is the same for the track artists because it's a single. What I think is happening is that there are 5 "MUSICBRAINZ_ALBUMARTISTID" and only 1 "ALBUMARTIST"

Exactly. I need corresponding `ALBUMARTISTS` to properly assign artist information. I can't just use `ARTISTS`, since Artists may be only a subset of Album Artists and thus will be missing some entries. What Auxio currently does is take that first MBID, combine it with the concatenated album artist. As part of #202, I'm not just going to remove support for it because of this edge case. I consider this a consequence of poor tagging rather than anything else. I hope this makes sense. @polyester2023

**Comment by polyester2023** [comment] 2023-12-21 04:04
Is it possible for auxio to also display the joint phrases rather than comma

**Comment by OxygenCobalt** [comment] 2023-12-21 04:09
If I'm getting the right idea, then yes, it will be part of #582 @polyester2023.
