### ISSUE TITLE
[Bug?] Auxio doesn't show up when connected to the car (Android Auto, and USB Audio)

### ISSUE THREAD

**Issue by ORIOLESFan02** [OxygenCobalt/Auxio#627] opened 2023-11-27 19:57 UTC
### Describe the Bug/Crash

1. Plug phone into car (one that supports android auto, or just one where you can do USB, as it shows nothing)
2. Play music (music plays, but there's no information. No artist, no song title, doesn't show how long it is, etc.)
3. You hear music, but you don't see anything in the android auto music player thingy (or your cars infotainment screen [no android auto])

### Describe the intended behavior

Music information should display on vehicle (infotainment and android auto)

### What android version do you use?

Android 14

### What device model do you use?

Pixel 7 Pro

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-11-27 22:22
Duplicate of #37. Auxio doesn't support android auto yet.

**Closed by OxygenCobalt** 2023-11-27 22:22 UTC
Labels: bug
