### ISSUE TITLE
Please Add Feature of Creating Playlists

### ISSUE THREAD

**Issue by Prateek0080** [OxygenCobalt/Auxio#427] opened 2023-04-20 09:12 UTC
Please Add Feature of Creating Playlists 

_Originally posted by @Prateek0080 in https://github.com/OxygenCobalt/Auxio/pull/418#issuecomment-1515990555_

**Comment by illdeletethis** [comment] 2023-04-20 10:37
duplicate of #36 
this is the pinned issue

**Closed** 2023-04-20 14:44 UTC
