### ISSUE TITLE
Use Playlists files (m3u)

### ISSUE THREAD

**Issue by Emporea** [OxygenCobalt/Auxio#868] opened 2024-09-12 19:00 UTC
### Description

It would be awesome if there were an option to use playlist as m3u files, instead of the internal database.

Manual Importing and Exporting is not sufficent for conveniently synthing changes in playlists over multiple devices.

### Other implementations

Other music players can use playlists by file, and changes to the playlist are also immediately written to the files. For example [Phonograph](https://github.com/chr56/Phonograph_Plus)

### Benefit

Read from and write to playlists in a given directory without manual importing or exporting. Changes are present immediately.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-09-13 22:21
Duplicate of #322. Android's method of exposing playlists is actually deprecated and extremely broken, hence why I use manual imports. Once I have direct filesystem access, I can work around it and index them myself.

**Closed by OxygenCobalt** 2024-09-13 22:21 UTC
Labels: enhancement
