### ISSUE TITLE
App crash on dark theme (< Android 11)

### ISSUE THREAD

**Issue by talal12bfk** [OxygenCobalt/Auxio#80] opened 2022-02-18 21:26 UTC
#### Describe the bug/crash:
it happens only if i've the dark theme on
i cant open the app after it closes until i delete the apps data and reset it (practicly)
ps. see the video

#### Steps To Reproduce the bug/crash:

1. Go to Auxio's settings set the the to be dark
2. play music
3. after finished close the app
4. when app is completly close (even in the background) try to restart it
5. app crashes until i reset it

#### Logs/Stack Traces:
its not possible because of lack of hardware :(

#### Screenshots:
https://user-images.githubusercontent.com/85613292/154762137-d1d4a10a-e30c-4099-a3ed-9333f46a8b3d.mp4

the videos had to be in bad quality because of github filesize restriction and my bad internet connection :)

#### Phone Information:

huawei, Y7, 8.0.0

#### Due Diligence:
- [ x] I have checked this issue for any duplicates.
- [ x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [ x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2022-02-18 22:11
Seems device-specific. Perhaps I can find an app that shows access to the logcat directly, if not, I'll try to identify it when I implement the crash screen I'm planning.

Quick question: Have you tried the test app in #78? If you are unable to install it due to the lack of hardware, it will be released in v2.2.1 tomorrow.

**Comment by OxygenCobalt** [comment] 2022-02-20 13:22
Yeah, it looks like you can't access the logcat without external hardware in one way or another. I'll need to implement a crash screen before I can continue.

**Comment by Der-Flip** [comment] 2022-02-24 12:52
Some more info:

When the in-App theme is selected opposite of the Systemtheme the app crashes on start-up:

- System darkmode enabled + in-App light Theme: app crashes
- System darkmode DISabled + in-app dark theme: App crashes
- System darkmode either enabled or disabled + in-app theme auto: app runs

Xiaomi Redmi9C
Android 10 (QP1A.190711.020)
MIUI Global 12.0.11 Stable

**Comment by OxygenCobalt** [comment] 2022-02-24 22:29
Strange. I've can't seem to reproduce this discrepancy on a physical Android 11 device nor a virtual Android 10 device. 

@Der-Flip Can you try to obtain a logcat for this crash? If you don't know how, the instructions to do that are in the bug issue template.

**Comment by OxygenCobalt** [comment] 2022-02-25 02:07
I've identified the issue. It's an insane race condition somehow triggered by a mismatched theme on android versions below 10 that somehow results in the fragment lifecycle being in an invalid state (but only on specific UIs like the playback panel). I hate this platform so much. At least I know what to do.

**Closed** 2022-02-25 02:38 UTC
Labels: bug, device-specific

**Comment by Der-Flip** [comment] 2022-02-25 06:26
> Can you try to obtain a logcat for this crash?
I've tried but i'm still new to android and quite unfamiliar and using the SDK kept me very hesitant, which is why I opted to do that video.

> I've identified the issue. I hate this platform so much. At least I know what to do.
You're a savior! :'D

> This issue should be fixed in version  2.2.2 or 2.3.0 given the severity.
Don't worry, take your time. We know how _not_ to cause it :)

By the way, do you know, why the colours are so desaturated when Android dark theme and in-App dark theme are enabled?

**Comment by OxygenCobalt** [comment] 2022-02-25 14:42
> By the way, do you know, why the colours are so desaturated when Android dark theme and in-App dark theme are enabled?

No, not really. I also can't seem to reproduce this on any of my physical/virtual devices. I'd imagine it's MIUI messing things up.

**Comment by talal12bfk** [comment] 2022-02-25 14:58
propably its a pretty lagy/bugy/locked up system im planning on rooting it
and flashing a custom more clean version of android.
