### ISSUE TITLE
Gapless Playback

### ISSUE THREAD

**Issue by azizikri** [OxygenCobalt/Auxio#576] opened 2023-09-18 14:38 UTC
### Description

Please create gapless playback like spotify

### Problem solved

its kinda weird in some albums when there is a gap between correlating song

### Other implementations

in spotify, they add the gapless menu toogle in the settings

### Benefit

this features allow more immersive experience when listening to some album

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2023-09-18 14:51
Duplicate of #110.

**Closed by OxygenCobalt** 2023-09-18 14:51 UTC
Labels: enhancement
