### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Koruy** [OxygenCobalt/Auxio#677] opened 2024-01-15 16:27 UTC
### Describe the Bug/Crash

Does not read music files from folders other than the music folder
![Screenshot_20240115_192530](https://github.com/OxygenCobalt/Auxio/assets/53151866/2db0a977-69f9-4753-b137-ba7a9594a087)

### Describe the intended behavior

Must read music files from folders other than the music folder

### What android version do you use?

Android 13

### What device model do you use?

Honor 70

### Bug report

[bug.zip](https://github.com/OxygenCobalt/Auxio/files/13941067/bug.zip)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-01-15 16:28
Dupe of #667

**Closed by OxygenCobalt** 2024-01-15 16:28 UTC
Labels: bug

**Comment by Koruy** [comment] 2024-01-15 16:33
Sorry, I'm not paying attention
