### ISSUE TITLE
Change non-repeat icon in music player notification

### ISSUE THREAD

**Issue by VoxelPrismatic** [OxygenCobalt/Auxio#837] opened 2024-07-23 13:07 UTC
### Description

When no repeat mode is selected, the icon should be something similar to ➡️

(you can also change nom-shuffle to something like `=>`)

### Problem solved

It is difficult to tell between the bold and normal variants of 🔁, so I don't know if it's repeating.

### Other implementations

They don't have shuffle buttons in the player notification

### Benefit

At a glance, you know if your long playlist is repeating properly

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment] 2024-07-25 03:11
Duplicate of prior issues:
- A straight arrow icon is not clearly representative of a repeat mode or shuffle state.
- Fading out shuffle-repeat icons makes it trivial to confuse with them being disabled
- Using a thicker icon to indicate the active state is an official recommendation of Material Design 3

**Closed by OxygenCobalt** 2024-07-25 03:11 UTC
Labels: enhancement

**Comment by VoxelPrismatic** [comment] 2024-07-25 18:57
Can you make it even thicker? Or is it just a different SVG being loaded? There is less than 2px change.

**Comment by OxygenCobalt** [comment] 2024-07-26 03:06
I am limited to what the Material Icon library provides, but maybe I can make it thicker @VoxelPrismatic.
