### ISSUE TITLE
Lyrics support (Sync, Normal)

### ISSUE THREAD

**Issue by ian1ilych** [OxygenCobalt/Auxio#251] opened 2022-09-26 15:36 UTC
Can you make lyrics support for songs that has lyrics in the phone's storage?
Different styles: (Normal: Scroll through texts from the song) (Sync: Synchronize the rhythm through text).

**Comment by OxygenCobalt** [comment] 2022-09-26 15:37
Duplicate of #190 #123 #86 #48 #19. I have only seen music apps get buggier when they add lyrics support. I will never add lyrics.

**Closed by OxygenCobalt** 2022-09-26 15:37 UTC
Labels: enhancement

**Comment by ian1ilych** [comment] 2022-09-26 18:43
I know, but I used some music players to use lyrics and the best choice for automatic lyrics adding is Oto Music.

**Comment by ian1ilych** [comment] 2022-09-26 18:48
And do you know? Oto Music is the best choice because it has its own music player dialog for file explorer, chrome cast support, lyrics for normal and sync, last.fm info on artists, best choices for the music player. So if you want to beat it, you need better functions that everyone wanted.

**Comment by ian1ilych** [comment] 2022-09-26 18:50
Did you know? In Java, you can make lyrics reading easier that Kotlin. I didn't checked it for myself but yeah.

**Comment by OxygenCobalt** [comment] 2022-09-26 19:04
I do not add features because other music players have them. In fact, it was the over-abundance of useless features in other apps that drove me to create Auxio in the first place. 

My goal is not to be the "best music player on android", neither is it to be the one with the most features. It is still first and foremost **for my own use**, and all features I accept are in line with that. 

If you want a feature-packed music player, just use Poweramp or Oto or FooBar. They have devs that are *paid* to develop their players, and thus have an incentive to add as much features as possible, and actually make the apps stable even with all of their features.

What about the complex players that are maintained by FOSS unpaid developers? They are all dead. Locked in the Android Q compatibility sandbox for all eternity as the cost of migrating their complexity to platform changes exceeds their time and commitment. They are confusing, unusable, and riddled with bugs, and their dismal state is what encouraged me to start Auxio 2 years ago.

I will try to avoid the fate of other FOSS players whenever possible, and if that means that I have to slim the feature set down to what I find reasonable, so be it. It ensures that I can continue to maintain this app even with the minimal time I have to develop it.

**Comment by ian1ilych** [comment] 2022-09-27 00:57
Understandable
